### ISSUE TITLE
flutter 跨平台的sdk

### ISSUE THREAD

**Issue by lianyagang** [wildfirechat/vue-pc-chat#107]
是否考虑兼容一波pc端flutter

**Comment by dd9913762113** [comment]
> 你好，目前还没有相关计划。

大佬，可以给个联系方式吗？
寻求帮助

**Comment by imndx** [comment]
> > 你好，目前还没有相关计划。
> 
> 大佬，可以给个联系方式吗？ 寻求帮助

微信：wfchat
