### ISSUE TITLE
会议分享屏幕时，需要在操作栏中加入成员管理按钮，见例图

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/vue-pc-chat#111]
![image](https://user-images.githubusercontent.com/34434072/137746771-b8a78dee-bbdf-4526-a1a9-2a6d49f4f603.png)

**Comment by imndx** [comment]
已支持实现类似功能

<img width="805" alt="image" src="https://user-images.githubusercontent.com/34434072/172032263-dfaa5c74-43ad-4c1e-ad1f-75f31f5dd6fe.png">
