### ISSUE TITLE
断网重连后 还显示网络断开  发条消息就好了

### ISSUE THREAD

**Issue by jie-L** [wildfirechat/vue-pc-chat#115]
期望：可以实时监听网络情况

**Comment by imndx** [comment]
demo上好像复现不了呀，可以用我们最新的demo测试下

**Comment by jie-L** [comment]
可以复现   断网后停留15分钟左右   需要等控制台不再打印connection status changed      重连之后依然显示网络断开      切换消息列表都不会重置      发消息才可以

**Comment by jie-L** [comment]
> 可以复现 断网后停留15分钟左右 需要等控制台不再打印connection status changed 重连之后依然显示网络断开 切换消息列表都不会重置 发消息才可以

@imndx

**Comment by heavyrain2012** [comment]
我们已经修改了重连时间，现在是最长20秒钟，请联系我们更新SDK

**Comment by jie-L** [comment]
> 我们已经修改了重连时间，现在是最长20秒钟，请联系我们更新SDK

反复测试还是存在这个问题   断网>15分钟   重连任何操作网络状态都为-1    发消息就正常

**Comment by imndx** [comment]
> > 我们已经修改了重连时间，现在是最长20秒钟，请联系我们更新SDK
> 
> 反复测试还是存在这个问题 断网>15分钟 重连任何操作网络状态都为-1 发消息就正常 (ps: 新版sdk好像有问题 开发者工具刷新后 一键登陆失败 connection status changed 0 切换旧sdk正常)

可以联系我们更新一下SDK

或者，刷新之后，检查一下连接状态，如果是已连接的话，直接进去就行。
