### ISSUE TITLE
截图是否可以隐藏当前窗口？截图背景不清晰，虚化效果明显。 聊天记录多选，点击收藏无反应。 UI页面是否可以添加阴影

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#123]
1、截图是否可以隐藏当前窗口？截图背景不清晰，虚化效果明显。
2、聊天记录多选，点击收藏无反应。
3、UI页面是否可以添加阴影

**Comment by imndx** [comment]
1、3：这两个问题，请你们根据产品设计，自行调整吧。
2. 请参考最新提交。48b2267

**Comment by Adar-Li** [comment]
关于问题2，代码提交的时候提交了无效代码，导致多选收藏失败，如图。
![image](https://user-images.githubusercontent.com/13981812/147400374-83af897b-e2ed-4048-b1ec-c060f2ca00a6.png)
多选收藏成功后，收藏页面看到的收藏内容不能展开，只能看到最多三条。
