### ISSUE TITLE
聊天页面，输入框中，点击回车后，会换行后，再发送，导致发送的文字，出现格式问题

### ISSUE THREAD

**Issue by meetmr** [wildfirechat/vue-pc-chat#130]
如果一段文字，我光标移动到文字中间点击回车，就会出现文字换行
代码 @keyup.enter="send($event)
建议改成  @keydown.enter="send($event)

**Comment by imndx** [comment]
谢谢反馈，欢迎给我们提 PR

**Comment by meetmr** [comment]
这是来自QQ邮箱的假期自动回复邮件。
