### ISSUE TITLE
聊天独立窗口

### ISSUE THREAD

**Issue by 1Silencer** [wildfirechat/vue-pc-chat#131]
会话可以单独拉出来作为独立窗口

**Comment by imndx** [comment]
你好，不太明白，可以截图示例下。

**Comment by 1Silencer** [comment]
![image](https://user-images.githubusercontent.com/44016268/147824047-23037721-632f-4df7-b37f-3ec303a9e97b.png)

**Comment by 1Silencer** [comment]
> 你好，不太明白，可以截图示例下。

![image](https://user-images.githubusercontent.com/44016268/147824083-6eabac38-75ec-4b09-b730-fe33eba33811.png)

**Comment by imndx** [comment]
你好，目前不支持，欢迎提交 pr
