### ISSUE TITLE
聊天过程中，如果发送网址链接，点击网址链接会打开内置浏览器，覆盖整个聊天页面，并且无返回按钮。

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#133]
聊天过程中，如果发送网址链接，点击网址链接会打开内置浏览器，覆盖整个聊天页面，并且无返回按钮。

**Comment by imndx** [comment]
demo 是通过浏览器来打开链接，没有这问题。

如果，demo 上能复现的话，请附上一个录像，我们看下到底怎么复现。

**Comment by imndx** [comment]
no response.
