### ISSUE TITLE
关于支持群链接邀请进群，是否能添加这个功能？谢谢

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#134]
关于支持群链接邀请进群，是否能添加这个功能？谢谢

**Comment by heavyrain2012** [comment]
这个功能属于应用功能，你们可以在网上查一下如何网页调起electron应用，然后把群信息传给electron应用。可以参考 https://blog.csdn.net/dengdongxia/article/details/105906975 这个链接

**Comment by heavyrain2012** [comment]
开发这个功能时还需要跟移动端对齐，所有端都使用相同的scheme，这样链接可以被所有客户端识别和处理

**Comment by imndx** [comment]
请参考 #128
