### ISSUE TITLE
pc 端共享屏幕的时候，清晰度是否可以通过调整分辨率选择设置？

### ISSUE THREAD

**Issue by dumingying** [wildfirechat/vue-pc-chat#136]
pc 端共享屏幕的时候，查看画面，文字显示不清晰，是否可以通过设置分辨率去调整清晰度。

**Comment by imndx** [comment]
设置分辨率，请看[这儿](https://github.com/wildfirechat/vue-pc-chat/blob/5d5014072a292f9038a363e6c92238285dd6d965/src/wfc/av/engine/avenginekit.js#L37)
