### ISSUE TITLE
wfc.deleteFriend会删除好友，但是聊天对话框依然存在，并且还可以继续发送消息

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#138]
在好友列表的详情页添加一个删除好友的按钮，wfc.deleteFriend确实会删除好友，但是聊天对话框依然存在，并且还可以继续发送消息

**Comment by imndx** [comment]
可以调用 ```store.deleteFriend```方法来删除好友，那里面做了删除会话，重新加载会话等操作。

**Comment by Adar-Li** [comment]
> 可以调用 `store.deleteFriend`方法来删除好友，那里面做了删除会话，重新加载会话等操作。

store里面没找到。。。deleFriend这个方法

**Comment by Adar-Li** [comment]
> 可以调用 `store.deleteFriend`方法来删除好友，那里面做了删除会话，重新加载会话等操作。

还是有个bug，比如我正在和你聊天，然后我删除你，聊天列表不存在，但是对话框还是存在的，还可以进行聊天

**Comment by heavyrain2012** [comment]
当对方删除你时，你会收到一个好友列表变更的事件，在单聊的界面收到这个事件后，判断一下对方是不是你的好友，如果不是好友，关掉窗口。同理会话列表也是如此
