### ISSUE TITLE
Win11，系统设置为英文，且系统用户名是中文时，无法写入wildfirechat.ini

### ISSUE THREAD

**Issue by gousiqi** [wildfirechat/vue-pc-chat#141]
win11，系统区域设置为英文，且系统用户名是中文时，无法向数据目录下写入wildfirechat.ini，导致getToken提供的clientId与connect时提供的clientId不一致，连接一直报错误码-7。
![image](https://user-images.githubusercontent.com/37241358/150325763-b5d91611-015b-45a5-a8fc-40d94a1ac261.png)

**Comment by heavyrain2012** [comment]
是不是在win10下也是同样的问题？

**Comment by gousiqi** [comment]
尝试过win10好像没办法更改系统区域和语言，只能恢复出厂设置，目前没有设备所以就没有验证过。

**Comment by gousiqi** [comment]
> 尝试过win10好像没办法更改系统区域和语言，只能恢复出厂设置，目前没有设备所以就没有验证过。

尝试过win10好像没办法更改系统区域和语言，只能恢复出厂设置，目前没有设备所以就没有验证过。

**Comment by gousiqi** [comment]
> 系统区域设置为英文，

win11中必现

**Comment by heavyrain2012** [comment]
关于clientiid，野火会获取到用户数据目录，生成一个uuid保存到用户数据目录下的wildfirechat目录内。猜测是系统设置为英文，使用系统api获取到的字符串是ascii，路径中包含用户名，因为用户名是中文，这样路径就没有办法用ascii正确表达了。

**Comment by heavyrain2012** [comment]
如果要支持中文路径，必须把区域设置为非英文才可以
