### ISSUE TITLE
在PC端传输文件功能优化问题

### ISSUE THREAD

**Issue by imndx** [wildfirechat/vue-pc-chat#142]
建议： 
1、建议在PC端优化大文件传输，完全与微信对应，直接在聊天页面发送，不需要通过大文件中转 
2、改进接收文件处理方式，支持默认文件存储路径（可在设置中配置），小文件直接下载接收，大文件确认接收，支持另存。
3、文件打开方式应改进直接支持打开，比如用shell方式。

**Comment by imndx** [comment]
问题3，请参考 a171110

**Comment by zhaozhen-king** [comment]
这问题的 1，2怎么解决呢？
