### ISSUE TITLE
优化内容

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#146]
1、禁用ctrl+shift+i快捷键，此快捷键会弹出控制台。
2、发送的消息应为普通文本并进行过滤、编码，严禁script，iframe等高危富文本标签。

**Comment by imndx** [comment]
> 2、发送的消息应为普通文本并进行过滤、编码，严禁script，iframe等高危富文本标签。

针对收到的消息，可以在```TextMessageContentView#textContent```里面进行过滤。

**Comment by imndx** [comment]
FYI: [459ef11](https://github.com/wildfirechat/vue-pc-chat/commit/459ef11ba4fd609da088346e4007f561e81d936e)
