### ISSUE TITLE
创建群组时，会自动进入到会话中，显示两条创建群组的通知，切换会话时，变成一条

### ISSUE THREAD

**Issue by heavyrain2012** [wildfirechat/vue-pc-chat#15]
可能是进入到会话时，通知消息已经被存下来了，还没有通过消息回调上来，等进入到会话后才收到消息的回调，需要排重

**Comment by heavyrain2012** [comment]
![Uploading 截屏2021-01-27 下午8.56.28.png…]()

**Comment by heavyrain2012** [comment]
![截屏2021-01-27 下午8 57 03](https://user-images.githubusercontent.com/34463389/105994146-369bfd00-60e2-11eb-82b9-042fb7deaaec.png)

**Comment by imndx** [comment]
复现不了呀
