### ISSUE TITLE
调用wfc.getUserInfo接口refresh参数传true时，接口返回的数据依然是从客户端本地数据库获取

### ISSUE THREAD

**Issue by simpleman315** [wildfirechat/vue-pc-chat#154]

**Comment by imndx** [comment]
是的，```wfc.getUserInfo```都是返回本地信息，如果```refresh```参数传```true```的，那么会从服务端拉取新的用户信息，如果确有更新的话，会通过```UserInfosUpdate```事件通知进行通知。

另外，```getUserInfoEx```会通过回调的方式返回用户信息

**Comment by simpleman315** [comment]
> 但是目前的实际情况是refresh传了true,并没有从服务端拉取新的用户信息
