### ISSUE TITLE
Proto updateRemoteMessageContent is not a function.

### ISSUE THREAD

**Issue by Muzummil** [wildfirechat/vue-pc-chat#155]
I used a function of proto.min.js file named "updateRemoteMessageContent" with all the valid parameters with types but in response, I am getting the type error of the function. I have checked the proto object and it is working fine with other functions but for this it is giving error. Screenshot attached for reference.
In order to reproduce it, you call the method with valid parameters.
![error](https://user-images.githubusercontent.com/48760089/154841398-99fe950d-f17b-4da6-90ee-175ee9c2a03b.jpeg)

**Comment by heavyrain2012** [comment]
这个功能是在22.1.12号加上的，且只加到electron15的那个版本上，如果不是这个版本，请发邮件给我们索要这个SDK
