### ISSUE TITLE
会议中是否可以添加更新最新头像的功能

### ISSUE THREAD

**Issue by dumingying** [wildfirechat/vue-pc-chat#156]
头像更新后，未触发更新头像，进入会议后获取到的头像不是最新的头像，

**Comment by imndx** [comment]
是别人的头像，还是自己的头像？

**Comment by dumingying** [comment]
所有人员的头像



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 下午4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/vue-pc-chat] 会议中是否可以添加更新最新头像的功能 (Issue #156)





 
是别人的头像，还是自己的头像？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by imndx** [comment]
在非主窗口，可以通过```IpcSub#getUserInfo```进行刷新用户信息了。
