### ISSUE TITLE
Reference error.

### ISSUE THREAD

**Issue by Muzummil** [wildfirechat/vue-pc-chat#157]
After updating to electron15 and merging with master I am facing this issue.
![image (1)](https://user-images.githubusercontent.com/48760089/154915617-e18894b6-ad7a-4c71-b195-acffe1440810.png)

**Comment by heavyrain2012** [comment]
代码是这个项目master分支最新的代码吗？master分支是electron15的代码，electron_8分支是electron8的代码

**Comment by Muzummil** [comment]
yes, it is merged with the master branch.

**Comment by heavyrain2012** [comment]
直接放到master分支的代理里可以吗，是不是merge引起的问题

**Comment by imndx** [comment]
```background.js ``` 文件是否和项目里面的完全一致？如果不一致的话，请确保，创建主窗口```BrowserWindow```的时候，包含以下属性：

```
       webPreferences: {
            scrollBounce: false,
            nodeIntegration: true,
            contextIsolation: false,
            nativeWindowOpen: true,
            webSecurity: false,
        },
```

**Comment by Muzummil** [comment]
After changing above and replacing the whole wfc folder, I am getting this error now.
![image](https://user-images.githubusercontent.com/48760089/155078441-99e0dd35-a69a-478b-ba46-0e8d1441317f.png)

**Comment by Muzummil** [comment]
If we downgrade electron to 8 with same everything works fine and upon calling the updateRemoteMessageContent method and error callback is returning error code 253.
![image](https://user-images.githubusercontent.com/48760089/155086176-89f4c27f-6bdd-40bf-9b5f-49604f74d20e.png)

**Comment by imndx** [comment]
253 表示消息不存在，请确认下。

**Comment by imndx** [comment]
> After changing above and replacing the whole wfc folder, I am getting this error now. ![image](https://user-images.githubusercontent.com/48760089/155078441-99e0dd35-a69a-478b-ba46-0e8d1441317f.png)

electron 15 时，remote 模块，需要这样引用： ```require('@electron/remote')```

**Comment by imndx** [comment]
```platform.js```也需要更新的

**Comment by Muzummil** [comment]
All the files are same and I was getting @electrom/remote error which is deprecated so I changed/removed but still getting this error.
![image](https://user-images.githubusercontent.com/48760089/155139320-4df1d795-4622-41be-b336-47c31c814a95.png)

**Comment by Muzummil** [comment]
Still happening even updating proto files.

**Comment by heavyrain2012** [comment]
我们测试过了，把邮件里的库文件直接到当前项目master分支最新代码，是可以正常运行的。请用当前项目只体验SDK进行验证，验证SDK是否是正常的。

**Comment by Muzummil** [comment]
Now we are able to call the method but upon calling it application is getting hanged and console is giving following exception.
![image](https://user-images.githubusercontent.com/48760089/155928702-9ff14a60-81f9-4445-bf41-d4e858ee5864.png)

**Comment by Muzummil** [comment]
If you can call and share the example of using this method then it will save lot of time and effort.

**Comment by heavyrain2012** [comment]
请在我们demo修改一下，能把问题复现出来，提个pr给我们，然后告诉我们如何复现问题的，我们验证确认后会去修改

**Comment by Muzummil** [comment]
Fixed
