### ISSUE TITLE
PC专业版SDK调用createGroup接口的时候，群主和群成员标识属性type的值错误

### ISSUE THREAD

**Issue by simpleman315** [wildfirechat/vue-pc-chat#160]
PC客户端调用SDK **createGroup**接口的时候，SDK调用到im服务后台的时候群主传的type值为0，群成员为2，正确的应该是群主传的type值为2，群成员为0

**Comment by heavyrain2012** [comment]
我们测试验证了，确实是有这个问题，稍后我们会重新给你们发布新的版本
