### ISSUE TITLE
[重构] 关于web项目迁移至pc项目的问题

### ISSUE THREAD

**Issue by JSoon** [wildfirechat/vue-pc-chat#162]
背景：由于历史原因，之前的客户端项目仅是一个web项目的套壳。近期，项目组计划将现有web项目迁移至pc项目，同时希望尽可能复用当前web项目代码。

请问有哪些需要注意的方面，或者说官方是否能够提供一个比较合适的指导方案呢？谢谢！

**Comment by imndx** [comment]
由于，```vue-chat```和```vue-pc-chat```的 UI 层代码是完全一致的，对 web 和 electron 平台做兼容处理，故从官方的```vue-chat```迁移到官方的```vue-pc-chat```，只需要替换```vue-pc-chat```里面的 sdk 即可。

如果对```vue-chat```进行了二次开发，那么还需要将相关的代码合并到```vue-pc-chat```
