### ISSUE TITLE
发送视频文件是否能够添加压缩/转码消息状态？

### ISSUE THREAD

**Issue by JSoon** [wildfirechat/vue-pc-chat#171]
如题，希望消息状态新增视频文件压缩/转码的状态，使得视频文件能且仅能在压缩/转码后进行发送，避免某些格式的视频使用video标签无法播放的问题。

微信类似功能如下图所示：

![image](https://user-images.githubusercontent.com/7589350/158145732-8d8f261e-68ec-4eca-b844-cdb756a12d1c.png)

**Comment by imndx** [comment]
发送的文件的时候，做一下检测，如果发现是不支持的视频文件，则先进行转码操作，转码成功之后，继续走发送流程。
