### ISSUE TITLE
Windows new message blink icon background. 

### ISSUE THREAD

**Issue by Muzummil** [wildfirechat/vue-pc-chat#172]
Our goal is to show background of windows icon in taskbar something like below.
![image](https://user-images.githubusercontent.com/48760089/158175658-079a0d07-05c5-4d94-8ee0-9d5794fdf782.png)
We have a function "execBlink" in background.js file and we want to trigger it manually i.e when we receive a new message in store or proto file. Is there any way to achieve this? We have tried with ipcMain and ipcRenderer but not receiving the call back in background.js file.
Putting the logic in store is not a valid way so is there other way to achieve this in accordance to existing structure of the application?

**Comment by imndx** [comment]
请参考下面这个方法的调用逻辑，通过```update-badge```事件，最终会触发```execBlink```
https://github.com/wildfirechat/vue-pc-chat/blob/06dacc1d7ffcafd43cb3d9e80d8e09a0ca684716/src/store.js#L1619-L1637

**Comment by Muzummil** [comment]
I did exactly the same but it is not triggering the callback, thanks for the response.
