### ISSUE TITLE
Windows开发环境下，热更新 background.js 导致闪退

### ISSUE THREAD

**Issue by Williamlifetime** [wildfirechat/vue-pc-chat#174]
![Snipaste_2022-03-17_17-21-56](https://user-images.githubusercontent.com/72646087/158778293-5c072083-962f-424c-8da6-8f82c4d0a236.png)

https://user-images.githubusercontent.com/72646087/158778331-7bd3592c-0ccc-49e8-9880-a02539076db1.mp4

具体复现流程可查看视频

项目正常启动后，修改 background.js 中代码保存，进程闪退抛出异常 -4082  Error: EBUSY: resource busy or locked

系统环境： Windows11 专业版
RAM： 8G
Node：v14.18.0

**Comment by imndx** [comment]
这个问题应当解决了，请用最新 demo 测试。
