### ISSUE TITLE
关于electron从15.3.4降级至13.6.9原因及影响范围确认

### ISSUE THREAD

**Issue by jpguo520** [wildfirechat/vue-pc-chat#176]
你好，想确认一下3/11把electron版本从15.3.4降到了13.6.9的原因是什么，如果有不兼容，可否提示一下具体体现在哪方面呢。
      由于我们之前是同步升级到了15.3.4版electron，期间改了很多版本升级导致的UI及功能性问题，如果知道本次不兼容的问题所在，也好快速判断出来影响范围，决定接下来是继续用15版，还是也同步退回到13版。
     再一个，3/4 vue-pc-chat的sdk更新，应该是新功能追加了吧，以上问题也直接导致我们接下来sdk的使用版本。
     鉴于此两方面的困扰，烦请指点迷津

**Comment by heavyrain2012** [comment]
1，从15.3.4降到13.6.9的原因是我们测试在linux上有兼容问题，在某些linux发行版本上15.3.4不稳定，降到13.6.9后在我们测试的所有平台上都很问题。降版本基本上没有要修改的，15+和13+的语法基本一致，你们可以测试看看。如果你们只有windows和mac，可以继续15.3.4
2，我们是不断的修改问题和增加功能的，如果SDK不匹配，可以发邮件给我们要求重新发给你们一个。

**Comment by jpguo520** [comment]
好的了解了。我们暂时没有linux的计划。继续使用15+
