### ISSUE TITLE
PC专业版SDK在给对方连续快速发消息的时候，会话里面的最后一条消息和消息框的最后一条消息不一致(大概率会出现)，会显示成消息框里面的倒数第二条

### ISSUE THREAD

**Issue by simpleman315** [wildfirechat/vue-pc-chat#177]
最新版本的SDK有这个问题，用老版本的SDK就不存在此问题

**Comment by imndx** [comment]
退出，重新登录之后，会正常吗？

**Comment by simpleman315** [comment]
> 

退出重新登录还是一样的

**Comment by heavyrain2012** [comment]
已经修正，请发邮件联系我们要最新的SDK。

问题的原因是发出去的消息不能确保完全有序，会话列表记录的最后一条跟发出去服务器处理完成的时序不能确保完全一致。我们修改后可以确保数据库中的消息最后一条（按照时间排序）跟会话的lastMessage是一致的，但UI上因为插入是按照发送顺序，在发送界面还有可能是不一致，但切换一下界面就一致了，如果要想修改这个问题就需要再每条消息发送成功后重新排序ui上的消息，如果要想发送消息绝对有序，就需要建立一个发送队列，只有消息发送成功后再发送下一条。我们认为这种问题没有必要处理，如果你们想要解决，请按照我们提示的方法来解决。

**Comment by simpleman315** [comment]
好的，非常感谢

**Comment by simpleman315** [comment]
> 照时间排序

我们用最新的SDK试了一下，还是存在该问题，而且是持久化的，重新退出在登录还是错误的，麻烦在帮忙看下

**Comment by heavyrain2012** [comment]
我们测试了，快速发送消息，会出现会话列表和消息列表不一致的情况，但关掉重新打开就恢复了。请给我们录像你们的测试过程，然后把协议栈日志发给我们分析
