### ISSUE TITLE
群主创建一个群，群成员接收到信息后，拉取groupInfo，群信息不对，群名称为群聊，没有ownerID

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#184]

**Comment by imndx** [comment]
由于涉及到网络交互，```wfc.getGroupInfo```等接口是异步返回，会先返回本地的群信息，如果本地不存在该群信息的时候，会返回一个只包含```groupId```的```NullGroupInfo```对象，并从服务端去拉取该群的群信息，拉取成功之后，会通过```EventType.GroupInfosUpdate```进行通知，上层监听到```EventType.GroupInfosUpdate```之后，再次获取群信息即可。

此外，获取群信息还有另外一个方法：```wfc.getGroupInfoEx```。该方法通过回调返回群信息，当本地不存在该群信息的时候，会从服务端拉取，然后通过回调返回群信息。

**Comment by imndx** [comment]
补充一下，针对用户信息，也有一个类似的方法：`getUserInfoEx`

**Comment by imndx** [comment]
一些参考代码：
```
// 在合适的地方添加事件监听，比如组件创建的时候
wfc.eventEmitter.on(EventType.UserInfosUpdate, this.onUserInfosUpdate);

// ....

onUserInfosUpdate(userInfos){
// 业务代码，比如更新 UI 等
}

// 组件销毁的时候，记得删除监听，否则会造成内存泄漏
wfc.eventEmitter.removeListener(EventType.UserInfosUpdate, this.onUserInfosUpdate);

```
