### ISSUE TITLE
传输文件进度回退

### ISSUE THREAD

**Issue by tttdiiiii** [wildfirechat/vue-pc-chat#185]
传输一个几十M的文件时出现了传输进度到40%-50%时突然变为10%，然后重新传输一遍，传输文件有时候还不成功，网速较差时经常出现该问题。

**Comment by tttdiiiii** [comment]
网速只有几十K到一两百K时复现率很高。

**Comment by imndx** [comment]
进度回退是由于网络异常导致重新发送导致的，可以考虑在 UI 层加上一些规避处理，比如发现进度回退的时候，保持当前进度。

**Comment by imndx** [comment]
最新代码，重构了文件上传逻辑，全部走上层上传。

另外，将大文件上传和普通文件夹上传合并了，可以直接在聊天窗口发送大文件了。
