### ISSUE TITLE
Large file upload exception

### ISSUE THREAD

**Issue by Muzummil** [wildfirechat/vue-pc-chat#194]
When we try to upload 200 MB or bigger zip file from desktop application then app gets stuck infinitely as it can be seen in the screenshots. Same file uploading works fine on mobile applications.
![image](https://user-images.githubusercontent.com/48760089/162164698-3be2ec3c-87fe-4849-ab8c-dd9c7ba254d0.png)

**Comment by imndx** [comment]
你好，大文件上传是在 UI 层处理的，你可以调试下：

https://github.com/wildfirechat/vue-pc-chat/blob/046a41d8c81118e823161ce3c314f71486473bb2/src/store.js#L831

**Comment by Muzummil** [comment]
I have debugged and request with file goes fine till wfc "getUploadMediaUrl" method and even proto file but after calling sdk method it crashes despite handling the error.

**Comment by imndx** [comment]
请把调用```wfc.getUploadMediaUrl```的参数打印出来看下

**Comment by Muzummil** [comment]
![image](https://user-images.githubusercontent.com/48760089/162423224-1c8275d8-eed8-45ab-9b79-dcbbe2af55b7.png)

**Comment by Muzummil** [comment]
Same parameters for 100mb file and that works fine.

**Comment by imndx** [comment]
我怀疑你们是直接调用了```wfc.uploadMedia```去上传超过 100M 的文件，这个方法只支持上传 100M 以内的文件。

请确认下下面这段代码，当大于 100M 之后，会走```store.sendBigFile```，相关逻辑都在 UI 层，不会导致崩溃。

https://github.com/wildfirechat/vue-pc-chat/blob/046a41d8c81118e823161ce3c314f71486473bb2/src/store.js#L884-L895

**Comment by imndx** [comment]
```im server```配置的文件存储是什么？

**Comment by Muzummil** [comment]
IM server itself is on ECS and files are saved on Alibaba cloud storage.

**Comment by heavyrain2012** [comment]
uploadBigFile 这个函数你们是不是修改过，看一下最新代码中的这个代码

**Comment by Muzummil** [comment]
@heavyrain2012 nothing is been changed in terms of functionality of the function, commented code will execute after the success(which is not happening), and try-catch was added for error handling apart everything else is the same.

**Comment by heavyrain2012** [comment]
> 请把调用`wfc.getUploadMediaUrl`的参数打印出来看下

看一下这个，把参数内容截图看一下，可能是参数跟实际要求的参数不一致

**Comment by imndx** [comment]
你好，你们调用 ```wfc. getUploadMediaUrl```时，少了一个参数```contentType```

https://github.com/wildfirechat/vue-pc-chat/blob/ec9f3dbc7dcac3f3993553e0c08c08bc37097c3a/src/wfc/client/wfc.js#L1612-L1621


https://github.com/wildfirechat/im-server/issues/474
