### ISSUE TITLE
输入框拖拽问题

### ISSUE THREAD

**Issue by heavyrain2012** [wildfirechat/vue-pc-chat#2]
现象：输入框可以拖拽更大，但不能拖拽的像微信一样小
期待：可以像微信一样，缩小到2/3行文字大小

**Comment by heavyrain2012** [comment]
拖拽还有问题，向上拖拽时，边框能够跟随鼠标，向下拖动到最低附近时，边框不能够随鼠标移动

**Comment by imndx** [comment]
是的，另外，还有一个问题是，如果没有调整过输入框的高度，切换会话时，输入框不能保持一致的高度。

**Comment by heavyrain2012** [comment]
还有一个问题，拖拽调整高度之后，需要记录下高度，关掉重新打开还要继续这个高度
