### ISSUE TITLE
文件下载敏感词保存问题

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#200]
文件下载的敏感词在保存时候，改成能作为文件名的字符

**Comment by imndx** [comment]
不太明白，能附上个截图之类的进行说不

**Comment by csd96** [comment]
![1649920848(1)](https://user-images.githubusercontent.com/72648453/163334486-d9c1e081-6548-410e-ae07-08be55554111.png)
下载的文件涉及敏感词 文件名会被转为*号 导致无法保存 有没办法 把转换的文件名还原

**Comment by imndx** [comment]
因为涉及到敏感词，消息的接收方无法知道敏感词内容，只能保存的时候手动修改一下。

**Comment by imndx** [comment]
或者保存文件的时候，检查下里面有没有```***```，有的话，替换成其他字符

https://github.com/wildfirechat/vue-pc-chat/blob/53a8e24e0ae273732ddff9a5a3b53ab2df3d6f5f/src/background.js#L470-L476

**Comment by csd96** [comment]
好的
