### ISSUE TITLE
会话中音视频通话的显示问题

### ISSUE THREAD

**Issue by zxm0613** [wildfirechat/vue-pc-chat#201]
音视频通话消息类型的 status 返回值为 0 或 undefined。
![da0443500e4eb39d3fa8a8ff5a430e5](https://user-images.githubusercontent.com/81342340/163342890-c4e5e751-814d-4e6a-b18d-01034070ce6e.png)
![98381df7d1b5473c3bdf3511bbe9772](https://user-images.githubusercontent.com/81342340/163342961-8c43ee92-0182-442a-b5dd-f4fd6fedf799.png)

**Comment by imndx** [comment]
请参考这个 commit 53a8e24e0ae273732ddff9a5a3b53ab2df3d6f5f
