### ISSUE TITLE
聊天信息会出现两次

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#202]
只发了一条信息，客户端却显示两次

**Comment by imndx** [comment]
重启应用，还显示两次吗？

**Comment by csd96** [comment]
消息发送的人 只显示一条     接收的人 会看到两条  两条消息id不同 时间也不同 差个20s左右

**Comment by csd96** [comment]
消息发送的人 只显示一条     接收的人 会看到两条  两条消息id不同 时间也不同 差个20s左右

**Comment by csd96** [comment]
消息发送的人 只显示一条     接收的人 会看到两条  两条消息id不同 时间也不同 差个20s左右

**Comment by imndx** [comment]
你到```wfc.js```里面，发送消息相关方法处加上日志，看下是不是发送了两次

**Comment by csd96** [comment]
这种情况是 偶尔会发生

**Comment by csd96** [comment]
撤回功能有问题 无论是哪个端撤回  撤回效果仅在 执行者这边 在接收者那边没有体现

**Comment by imndx** [comment]
> 撤回功能有问题 无论是哪个端撤回 撤回效果仅在 执行者这边 在接收者那边没有体现

demo 上没问题，可能是你们上层的改动导致的。

**Comment by heavyrain2012** [comment]
> 撤回功能有问题 无论是哪个端撤回 撤回效果仅在 执行者这边 在接收者那边没有体现

也有可能是服务器或者SDK的问题，请更新最新的IM服务和客户端SDK试试

**Comment by imndx** [comment]
no response.
