### ISSUE TITLE
拖拽发送有点问题

### ISSUE THREAD

**Issue by zxm0613** [wildfirechat/vue-pc-chat#206]

**Comment by imndx** [comment]
什么问题？请截图或者录像示例下。

**Comment by zxm0613** [comment]
拖拽发送到当前聊天无反应并报错，
![image](https://user-images.githubusercontent.com/81342340/164136235-0dc47fd4-2194-4a40-a38e-f3adf78f1981.png)
拖拽到其他聊天是正常的

**Comment by imndx** [comment]
你好，demo 上无法复现。
