### ISSUE TITLE
正在聊天的联系人，点击删除，报错。鼠标移动到另外一个联系人，直接删除，会连带着没有删除成功的联系人一起删除掉

### ISSUE THREAD

**Issue by wmingmqing** [wildfirechat/vue-pc-chat#211]
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/58499228/164591411-75bd41a9-0d81-437e-9fa8-1c3e48d22c82.png">
正在聊天的联系人，点击删除，报错。鼠标移动到另外一个联系人，直接删除，会连带着没有删除成功的联系人一起删除掉

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/58499228/164591506-82a2dd10-8a95-4b18-b83c-ab94e47c3b19.png">
window点击zh这个没有响应，mac可以

**Comment by imndx** [comment]
请联系我们更新 SDK。
