### ISSUE TITLE
截图点击确认按钮，聊天输入框会显示两张相同的截图。

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#214]
截图点击确认按钮，聊天输入框会显示两张相同的截图。
目前有部分用户出现这个问题，您看下是否能复现。

**Comment by imndx** [comment]
我们没有复现，请问下出现问题的用户那边是必现的吗？

可能是快速点击确认按钮的问题不？

这个可能是所依赖的```electron-screenshots```截图插件的 bug，可能升级下依赖试试

**Comment by Adar-Li** [comment]
> 我们没有复现，请问下出现问题的用户那边是必现的吗？
> 
> 可能是快速点击确认按钮的问题不？
> 
> 这个可能是所依赖的`electron-screenshots`截图插件的 bug，可能升级下依赖试试

electron-screenshots升级了之后，截图会报错

**Comment by imndx** [comment]
> > 我们没有复现，请问下出现问题的用户那边是必现的吗？
> > 可能是快速点击确认按钮的问题不？
> > 这个可能是所依赖的`electron-screenshots`截图插件的 bug，可能升级下依赖试试
> 
> electron-screenshots升级了之后，截图会报错

那 debug 下，给我们提个 PR 呗

**Comment by Adar-Li** [comment]
> > > 我们没有复现，请问下出现问题的用户那边是必现的吗？
> > > 可能是快速点击确认按钮的问题不？
> > > 这个可能是所依赖的`electron-screenshots`截图插件的 bug，可能升级下依赖试试
> > 
> > 
> > electron-screenshots升级了之后，截图会报错
> 
> 那 debug 下，给我们提个 PR 呗

#221 您看下

**Comment by imndx** [comment]
请确认下：是截图了两次，还是往输入框插入了两次？

然后，加入类似防抖动，一次操作之后，直接忽略多长时间内的操作。

**Comment by Adar-Li** [comment]
> 请确认下：是截图了两次，还是往输入框插入了两次？
> 
> 然后，加入类似防抖动，一次操作之后，直接忽略多长时间内的操作。

看用户反馈是往输入框插入了两次，我看下您这块的逻辑，加一下类似防抖动试一下。
