### ISSUE TITLE
请问下， 群禁言需要怎么操作？

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#223]
禁言整个群和禁言单个用户，客户端怎么操作？

**Comment by imndx** [comment]
现在 pc/web 端没有相应 UI，api的话，请参考```wfc.modifyGroupInfo```

另外，请参考下：[群常见问题](https://docs.wildfirechat.cn/blogs/%E7%BE%A4%E7%9A%84%E4%B8%80%E4%BA%9B%E7%BB%86%E8%8A%82%E9%97%AE%E9%A2%98.html?h=%E7%A6%81%E8%A8%80)

**Comment by Adar-Li** [comment]
> 现在 pc/web 端没有相应 UI，api的话，请参考`wfc.modifyGroupInfo`
> 
> 另外，请参考下：[群常见问题](https://docs.wildfirechat.cn/blogs/%E7%BE%A4%E7%9A%84%E4%B8%80%E4%BA%9B%E7%BB%86%E8%8A%82%E9%97%AE%E9%A2%98.html?h=%E7%A6%81%E8%A8%80)

好的 谢谢
