### ISSUE TITLE
是否能新增一个搜索聊天记录的功能？

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#225]
是否能新增一个搜索聊天记录的功能？

**Comment by imndx** [comment]
现在已经有搜索聊天记录功能的，请看下 demo

**Comment by Adar-Li** [comment]
> 现在已经有搜索聊天记录功能的，请看下 demo

是在聊天列表上面的搜索框内搜索吗？

**Comment by imndx** [comment]
是的

**Comment by Adar-Li** [comment]
> 是的

我看了下，是弹出一个窗口进行搜索，是否能像合并到一起？

**Comment by imndx** [comment]
> > 是的
> 
> 我看了下，是弹出一个窗口进行搜索，是否能像合并到一起？

可以的，你参考下 demo 怎么的，可以自行实现。
