### ISSUE TITLE
electron version to 13.6.9 版本的，无法发送桌面通知(测试环境win10)

### ISSUE THREAD

**Issue by China-ls** [wildfirechat/vue-pc-chat#226]
系统是win10 ltsc 2019 1809版, 内部版本177633.2803
1.缩小界面，收到新消息无系统通知
2.直接调用store.notify方法也无法发送通知

**Comment by imndx** [comment]
你好，我们用 demo 测试了下，是正常的。

请问，在你们的系统上，demo 工作正常吗？

**Comment by imndx** [comment]
no response
