### ISSUE TITLE
getUnreadCount 方法 unread 参数返回有未读条数，但是没有未读消息了。

### ISSUE THREAD

**Issue by zxm0613** [wildfirechat/vue-pc-chat#228]
![012e12f562e1da7139efa1ccf44ac1c](https://user-images.githubusercontent.com/81342340/168033335-d0ac9196-3834-4eac-b970-9430f25bce7c.png)

**Comment by heavyrain2012** [comment]
已经查清了，是客户二次开发引入的问题
