### ISSUE TITLE
永久删除聊天记录和会话后，重新同步数据，产生空会话

### ISSUE THREAD

**Issue by Janseon** [wildfirechat/vue-pc-chat#232]
某个会话聊天记录已经被清空了（包括前端和后端的记录都被清空），会话也被删除。切换其他帐号后回来，或者清除app的缓存，重新登录该帐号，就会一直存在这个空的会话。
安卓，ios和pc都会有这样的问题。

通过打印同步回来的消息，然后跟会话列表里面的用户的uid与私聊消息的target做比较。发现同步回来的消息并没有找到对应空会话的消息。

请问会话列表是根据同步回来的消息生成的还是怎样生成的？以及如何避免这个产生空会话的问题。

**Comment by heavyrain2012** [comment]
这是因为协议栈内有会话同步功能，协议栈会根据会话阅读记录来生成会话。如果只清空消息没有删除会话，卸载重装应用就会自动生成，如果想要删除，可以在删除消息时，同时删除会话，删除会话后应该就不会在生成了（但之前有个bug，需要更新到最新才行）。

所以：
1. 客户端都升级到最新。
2. 客户端清空消息时，同时要调用删除会话。

这样以后就不会出现删除过会话换端登陆再出现空会话。

**Comment by heavyrain2012** [comment]
另外一种办法时获取会话出来，如果没有最后一条消息，就不显示这个会话

**Comment by Janseon** [comment]
> 另外一种办法时获取会话出来，如果没有最后一条消息，就不显示这个会话

**Comment by Janseon** [comment]
1、那些阅读记录是指userSetting里面的已读时间吗？是否包括置顶、静默这些设置？
2、过滤掉空的会话，也会把新建的私聊空会话也会过滤吧？
3、我们的需求：客户端永久清空了某个会话的聊天记录，或者后端执行定期永久清理了聊天记录后；客户端下次重新同步数据时，不会出现空的会话
