### ISSUE TITLE
群组聊天记录无法获取远程会话记录

### ISSUE THREAD

**Issue by xiaoyiebukuang** [wildfirechat/vue-pc-chat#235]
用户在设备A登录账号在群组中发言，之后更换设备B重新登陆账号，群组中没有之前设备A的聊天记录

**Comment by imndx** [comment]
demo 上可以复现吗？这边没有复现。

**Comment by xiaoyiebukuang** [comment]
自己建立的群聊没有问题，好像是后台自动创建的公司群有这个问题，这个需要注意什么吗

**Comment by imndx** [comment]
IM-Server的配置文件里面，有查看群历史聊天记录相关的配置。
```
## 群默认是否开启历史消息，当开启时群成员可以查看加入之前的历史消息，关闭时只能看加入之后的消息。群主或管理员可以修改
group.history_message false
```

1. 如果通过  APP 创建群聊的话，群是否开启历史消息，由上面的配置决定
2. 如果通过```server api```创建群聊的话，群是否开启历史消息，由群信息里面的```history_message```字段决定

**Comment by imndx** [comment]
no response
