### ISSUE TITLE
PC端是否有清除聊天记录的功能？

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#241]
消息列表点击右键删除对应的对话框，优先删除本地聊天记录，且下次登录时，删除的对话框聊天记录为空，同微信效果。
是否能有一个清空全部聊天记录的功能，可分为本地清空、远程清空等。

**Comment by heavyrain2012** [comment]
野火IM的会话和消息是分开的，可以删除会话时同时删除消息，你们改一下UI的删除处理就行。现在有远程清空的接口，可以删除远程消息

**Comment by Adar-Li** [comment]
> 野火IM的会话和消息是分开的，可以删除会话时同时删除消息，你们改一下UI的删除处理就行。现在有远程清空的接口，可以删除远程消息

我看现在远程清空是一条信息一条信息删除，可以删除整个对话框吗？

**Comment by Adar-Li** [comment]
> 有个这个接口 clearRemoteConversationMessages

好的 我看下

**Comment by Adar-Li** [comment]
> 有个这个接口 clearRemoteConversationMessages

我看删除会话 removeConversation这个接口，有个clearMsg这个bool值，这个值不是清空聊天记录的值吗？我设置了true不生效

**Comment by heavyrain2012** [comment]
设置为true是清除本地消息，当下次再进入会话时，会自动拉取远程消息，这样的感觉就是进入会话又出现消息了。有两种处理办法，一种是调用清理远程消息，这样消息就真的被删除了。另外一个办法就是进入会话不再自动拉取远程消息。请你们选择那种方式或者保持现状

**Comment by Adar-Li** [comment]
> 设置为true是清除本地消息，当下次再进入会话时，会自动拉取远程消息，这样的感觉就是进入会话又出现消息了。有两种处理办法，一种是调用清理远程消息，这样消息就真的被删除了。另外一个办法就是进入会话不再自动拉取远程消息。请你们选择那种方式或者保持现状

好的 明白了 谢谢
