### ISSUE TITLE
收藏附件和聊天附件是否能分开存放？

### ISSUE THREAD

**Issue by Adar-Li** [wildfirechat/vue-pc-chat#242]
由于用户附件过多，我们这边定时清理OSS上用户附件，导致用户收藏的附件不能下载或不能打开。
收藏附件和聊天附件是否能分开存放？

**Comment by heavyrain2012** [comment]
请检查IM服务对象存储的配置，可以为每种类型的文件分别放到不同的桶中，这样会话内的文件可以定期删除，头像和收藏要永久保留

**Comment by Adar-Li** [comment]
> 请检查IM服务对象存储的配置，可以为每种类型的文件分别放到不同的桶中，这样会话内的文件可以定期删除，头像和收藏要永久保留

针对收藏系列的附件，附件有对应的标识吗？
