### ISSUE TITLE
pc客户端 鼠标侧键问题

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#246]
pc客户端会监听鼠标侧键 返回到登录页面 ，
点击登录按钮后再按一下 不等手机确认登录 会直接跳过登录进入。

**Comment by imndx** [comment]
> 点击登录按钮后再按一下 不等手机确认登录 会直接跳过登录进入。

**Comment by csd96** [comment]
客户端会监听 鼠标侧键 向前向后  导致可以直接侧键返回到登录页  在侧键跳进应用页

**Comment by imndx** [comment]
demo 上现在还能复现吗？登录页到主页面的导航方式是 ```replace```，不应当能后退回去的。

**Comment by csd96** [comment]
demo 还没测试 我们客户端也只是偶尔会触发返回

https://user-images.githubusercontent.com/72648453/184055430-c3ba9a17-d87e-43c6-bbfb-6721160c6d77.mp4

**Comment by imndx** [comment]
会不会你们的改动导致的，demo 上，我们复现不了。
