### ISSUE TITLE
是否能有文件接收提示

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#247]
接收文件成功后进行消息提示。

**Comment by imndx** [comment]
比如怎么提示呢？

你搜索一下```file-downloaded```，下载文件完成之后，有这个事件。

**Comment by csd96** [comment]
![image](https://user-images.githubusercontent.com/72648453/179444369-d19a2250-07cb-4c40-9690-0de570bb8031.png)
类似这样的

**Comment by imndx** [comment]
> ![image](https://user-images.githubusercontent.com/72648453/179444369-d19a2250-07cb-4c40-9690-0de570bb8031.png) 类似这样的

这条插入的提示，会一直存在吗？还是重新进入会话，就没了？
