### ISSUE TITLE
无法拖拽文件至输入框

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#253]
![disable](https://user-images.githubusercontent.com/72648453/185352051-a890d5ea-e699-43c0-b8a3-0df152dc10b7.jpg)
系统: windows11

**Comment by csd96** [comment]
是权限原因

**Comment by imndx** [comment]
> 是权限原因

你好，请问下，你们是怎么解决的呢？

**Comment by csd96** [comment]
目前是选择修改注册表

**Comment by imndx** [comment]
> 目前是选择修改注册表

好的，谢谢反馈，再请问下，具体是没有什么权限？

**Comment by csd96** [comment]
win10也有这样的文件权限问题 在专业版的win10有个禁止拖拽的权限https://product.pconline.com.cn/itbk/software/dnyw/1704/9164121.html
win11 https://www.cnblogs.com/lijin-note/p/16542536.html 设置了一个 enableLUA 把1变成0 
具体的我也不太清楚 目前找到这两个解决方法

**Comment by imndx** [comment]
> win10也有这样的文件权限问题 在专业版的win10有个禁止拖拽的权限https://product.pconline.com.cn/itbk/software/dnyw/1704/9164121.html win11 https://www.cnblogs.com/lijin-note/p/16542536.html 设置了一个 enableLUA 把1变成0 具体的我也不太清楚 目前找到这两个解决方法

谢谢分享
