### ISSUE TITLE
发送文件的内存泄漏问题

### ISSUE THREAD

**Issue by w3cways** [wildfirechat/vue-pc-chat#255]
window 10 64位
用master 分支，启动后，截图（可以截稍微大一点，这样看内存泄漏明显一点）
然后发送图片
然后会进入到proto.min.js中如图所示的判断内
<img width="664" alt="23f78c926be2015eaa38d65d8c7e5ff" src="https://user-images.githubusercontent.com/6859510/186158309-52f0596b-f404-4f33-a658-bd58e6e78b26.png">
在下方打个断点，执行下去的时候，就能看到内存泄漏，无法回收

也尝试过发送成功后  messge.messageContent.file = null 还是一样

**PS:执行完new File()后，是主进程内存会增长且不会回收**

**Comment by imndx** [comment]
补充一点信息：
1. 和```electron/remote```可能没关系。
2. 把 ```&& message.messageContent.file```判断去掉，然后发送大文件更好复现问题

具体内存泄漏原因，还在调查

**Comment by imndx** [comment]
已解决，请拉取 [dev-remove-remote](https://github.com/wildfirechat/vue-pc-chat/tree/dev-remove-remote)分支进行测试
