### ISSUE TITLE
国产机光标未定位在输入框时，截图无法粘贴；其他图片复制粘贴也不生效；

### ISSUE THREAD

**Issue by zxm0613** [wildfirechat/vue-pc-chat#261]

**Comment by imndx** [comment]
目前使用[electron-clipboard-ex](https://github.com/kenan2002/electron-clipboard-ex)，该库不支持 Linux，可以大家一起研究下

**Comment by imndx** [comment]
[Electron clipboard api](https://www.electronjs.org/docs/latest/api/clipboard)
