### ISSUE TITLE
PC端SDK 缺少  getMessagesByTimestamp API

### ISSUE THREAD

**Issue by clg0118** [wildfirechat/vue-pc-chat#262]
下面是：Android SDK 中的API
`/**
 * 按照时间戳获取会话消息
 *
 * @param conversation 会话
 * @param contentTypes 消息类型列表
 * @param timestamp    时间戳
 * @param before       true, 获取fromIndex之前的消息，即更旧的消息；false，获取fromIndex之后的消息，即更新的消息。都不包含fromIndex对应的消息
 * @param count        获取消息条数
 * @param withUser     只有会话类型为{@link Conversation.ConversationType#Channel}时生效, channel主用来查询和某个用户的所有消息
 * @param callback     消息回调，当消息比较多，或者消息体比较大时，可能会回调多次
 */
public void getMessagesByTimestamp(Conversation conversation, List<Integer> contentTypes, long timestamp, boolean before, int count, String withUser, GetMessageCallback callback) {
    if (callback == null) {
        return;
    }
    if (!checkRemoteService()) {
        callback.onFail(ErrorCode.SERVICE_DIED);
        return;
    }

    try {
        mClient.getMessagesInTypesAndTimestampAsync(conversation, convertIntegers(contentTypes), timestamp, before, count, withUser, new IGetMessageCallback.Stub() {
            @Override
            public void onSuccess(List<Message> messages, boolean hasMore) throws RemoteException {
                mainHandler.post(() -> callback.onSuccess(messages, hasMore));
            }

            @Override
            public void onFailure(int errorCode) throws RemoteException {
                mainHandler.post(() -> callback.onFail(errorCode));
            }
        });
    } catch (RemoteException e) {
        e.printStackTrace();
        mainHandler.post(() -> callback.onFail(ErrorCode.SERVICE_EXCEPTION));
    }
}`

**Comment by imndx** [comment]
已添加
