### ISSUE TITLE
是否可做成像微信这种，有草稿的时候这个时间还是之前的最新消息时间，而非草稿时间？

### ISSUE THREAD

**Issue by zxm0613** [wildfirechat/vue-pc-chat#263]

**Comment by heavyrain2012** [comment]
我这里有4个平台的微信，都是当前最新版本，各种情况如下
1，android端，版本 8.0.27，草稿存储时会话时间变成当前时间，当草稿删除时，会话变回最后一条消息的时间。
2，iOS端，版本8.0.27，草稿存储时会话时间变成当前时间，当草稿删除时，会话时间保持不变（还是存储时间）。
3，Mac端，版本3.5.5.18，跟iOS端表现一致。
3，Windows端，版本3.7.6.44，草稿存储时会话时间不变，但会话跑到最顶端，当草稿删除时，会话时间保持不变位置也不变

猜测iOS和Mac端是一个团队做的，这样4个平台三个团队实现的结果各不一样。对于野火来说，除了web端和小程序端外，其他端都是统一的，所以只能选择一种方案。野火之前是草稿变动时都会更新当前时间，现在改成跟android一样。请更新SDK测试。
