### ISSUE TITLE
会议中 ，pc端与移动端会议互相挤掉，其他成员的音视频状态显示不准确，

### ISSUE THREAD

**Issue by dumingying** [wildfirechat/vue-pc-chat#269]

**Comment by heavyrain2012** [comment]
不支持多端拨打音视频，必须先挂掉一端再加入另外一端

**Comment by dumingying** [comment]
不是拨打音视频，，场景是：pc 与移动端登录同一个账号，pc 已经在会议中了，移动端再进入会议，会把pc挤掉，这时候移动端里面查看 互动模式下的成员，音视频状态都是不对的，
