### ISSUE TITLE
这个PC版的项目能用社区版本的server吗？

### ISSUE THREAD

**Issue by mailes** [wildfirechat/vue-pc-chat#272]
是支持Mac win linux  还是只支持 linux?

在官网收费项目里面看的 稀里糊涂的。不明白这个到底你们怎么收费的。

**Comment by heavyrain2012** [comment]
都支持，PC SDK是收费的，win+mac sdk是2.9W，linux的sdk是每个架构2.9W。pc sdk不依赖于专业版IM服务，所以可以搭配社区版IM服务使用。pc sdk可以先试用，试用之后再购买，试用方法 https://docs.wildfirechat.cn/trial/

**Comment by mailes** [comment]
> 都支持，PC SDK是收费的，win+mac sdk是2.9W，linux的sdk是每个架构2.9W。pc sdk不依赖于专业版IM服务，所以可以搭配社区版IM服务使用。pc sdk可以先试用，试用之后再购买，试用方法 https://docs.wildfirechat.cn/trial/

了解了 感谢。
