### ISSUE TITLE
pc版本日志的路径能够自己指定，里面的文件夹名字也能够自己指定

### ISSUE THREAD

**Issue by li-ld** [wildfirechat/vue-pc-chat#274]
原来的文件名如下 ： C:\Users\{登电脑登录用户名}\AppData\Roaming\wildfirechat\{用户Id}\wfchat_{日期}.xlog
其中的wildfirechat 和 wfchat可以自己指定名称

**Comment by heavyrain2012** [comment]
路径中的wildfirechat 可以根据 https://docs.wildfirechat.cn/faq/pc.html 问题11来处理。wfcha现在还不支持修改，我们估计下周三之前能够发个版本支持修改日志名

**Comment by heavyrain2012** [comment]
或者这个wfchat_{日期}.xlog 改成比较中立的名字，比如 proto_{日期}.xlog 是不是可以？

**Comment by li-ld** [comment]
> 或者这个wfchat_{日期}.xlog 改成比较中立的名字，比如 proto_{日期}.xlog 是不是可以？

最好是自定义好一些
