### ISSUE TITLE
请问vue-pc-chat里面要添加发送表情包功能，该如何添加？

### ISSUE THREAD

**Issue by zxinyang2019** [wildfirechat/vue-pc-chat#279]
我看了文档和相关代码，没有找到发送表情的相关代码，只有配置的说明，最好有示例代码，谢谢！

**Comment by imndx** [comment]
请看下这个 issue #216 

另外，动态表情是基于[V-Emoji-Picker](https://github.com/imndx/V-Emoji-Picker)开发的
