### ISSUE TITLE
客户端手动设置未读消息 tray未有闪烁

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#283]
sdk 是 10.24替换的 在此之前是正常的
客户端手动设置未读消息 tray未有闪烁
安卓端手动设置未读 tray会闪烁

**Comment by imndx** [comment]
请问是调那个 api 手动设置未读消息？

**Comment by csd96** [comment]
![image](https://user-images.githubusercontent.com/72648453/199414207-a41edc4b-9501-4222-a158-6eaec07da991.png)
demo上也是没有闪烁
