### ISSUE TITLE
发送新消息，pc端在windows下角标不同步问题

### ISSUE THREAD

**Issue by jeessu** [wildfirechat/vue-pc-chat#284]
1. 打开pc端（windows）和安卓端，登录同一个用户。
2. 会话同时收到消息，正常情况下角标同时会累加。一端查看后，另一端角标正常会清除。

**问题现象：**
一、 现在偶现，安卓端点击查看其中一个会话后（正常pc端的角标会清0），现在pc端的角标不再清掉，后续收到新消息后会继续累加角标数量（所有会话都角标不一致了），且所有的会话可以正常收到消息。
二、重新登录后，角标问题也还是出错。除非杀掉进程后重新登录角标就正常了

**问题分析：**
1. 通过抓包分析，在某一次UN后，就不再发起UG了。后续再发起UN都不会再发起UG。
2. 出现问题的网络比较差，可能是弱网环境下导致
**3. 目前怀疑是pc端的sdk底层有问题引起**
---望解答，谢谢！！

**Comment by imndx** [comment]
请问，demo 上能复现吗？

**Comment by jeessu** [comment]
> 

是偶现的。我们有买了你们的pc端sdk服务，目前问题没必现。

**Comment by jeessu** [comment]
@imndx  是偶现的。我们有买了你们的pc端sdk服务，目前问题没必现。

**Comment by jeessu** [comment]
@imndx @heavyrain2012  是偶现的。我们有买了你们的pc端sdk服务，用的是最近的新版本，目前问题没必现。

**Comment by jeessu** [comment]
@imndx @heavyrain2012 @imhao183 @siqiii 大佬好，我这边看了xlog日志 怀疑问题是腾讯的mars组件导致的，可以告知一下，你们这边较新版本sdk的mars是用什么版本吗？

**Comment by jeessu** [comment]
@imndx @heavyrain2012 @imhao183 @siqiii 大佬好，我这边看了xlog日志 怀疑问题是腾讯的mars组件导致的，可以告知一下，你们这边较新版本sdk的mars是用什么版本吗？

**Comment by imndx** [comment]
请你先确认下是是不是上层的问题：

可以在控制台输入：```__wfc.getUnreadCount([0,1,2], [0])```获取未读数，这个未读数和 UI 层无关

**Comment by imndx** [comment]
no response
