### ISSUE TITLE
不退出应用的情况下，切换账号xlog日志打印位置错误

### ISSUE THREAD

**Issue by yoffey** [wildfirechat/vue-pc-chat#288]
问题描述：用野火官方试用的PC端，先扫码登录账号A，然后再点击切换账号，退出到扫码界面，扫码登录账号B，查看发现账号B的用户文件夹下面没有生成xlog文件，查看发现账号A的文件夹下xlog的时间有更新，在A的xlog日志里面有查看到B的账号信息

**Comment by imndx** [comment]
已解决
