### ISSUE TITLE
electron8 mac系统打包package 会出现python报错

### ISSUE THREAD

**Issue by whwhz** [wildfirechat/vue-pc-chat#289]
![image](https://user-images.githubusercontent.com/31263663/201240596-10698651-8a61-42c5-9431-a37ea8ca31d8.png)
Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT

![image](https://user-images.githubusercontent.com/31263663/201240656-75bf46dc-317a-4111-a37f-c28a9c56439a.png)
本机python2.7.18已安装在其他目录 只是/usr/bin/python 系统目录下只有一个python3 不存在python 请问这个怎么更改

系统环境macos13.0 (22A380)

**Comment by imndx** [comment]
可以参考下这儿: https://github.com/electron-userland/electron-builder/issues/6726

**Comment by imndx** [comment]
> 可以参考下这儿: [electron-userland/electron-builder#6726](https://github.com/electron-userland/electron-builder/issues/6726)

简单说，就是先更新一下 ```electron

> 可以参考下这儿:
> 
> [electron-userland/electron-builder#6726](https://github.com/electron-userland/electron-builder/issues/6726)
> 
> [nklayman/vue-cli-plugin-electron-builder#1701](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1701)

简单说，就是先更新下```electron-builder```版本试试，可以先试下同步到和 demo 一样的版本
