### ISSUE TITLE
其他应用内的聊天图片拖到这个im聊天工具内会发送不了，测试从微信拖图片是可以的，希望官方大佬解决

### ISSUE THREAD

**Issue by wi8539** [wildfirechat/vue-pc-chat#294]
![微信图片_20221122153332](https://user-images.githubusercontent.com/44495705/203252923-53bb67c7-5dc3-408a-bf8e-3d149e02bfb3.png)

**Comment by wi8539** [comment]
测试了还是不行

**Comment by imndx** [comment]
> 测试了还是不行

请提供一下复现路径

**Comment by wi8539** [comment]
你从whatsapp平台聊天窗口是无法拖动图片到这个工具内的
