### ISSUE TITLE
切换外接音视频设备无效，

### ISSUE THREAD

**Issue by dumingying** [wildfirechat/vue-pc-chat#300]

**Comment by imndx** [comment]
这个是在 UI 层做的，你们调下

可以参考下面链接：
https://stackoverflow.com/questions/61275592/setsinkid-only-works-with-audio-and-not-new-audio
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

**Comment by imndx** [comment]
外接音频输入设备的话，已经解决了，请用最新代码测试。
