### ISSUE TITLE
移动端拨打音视频通话，pc接听后， 移动端挂断，pc端无法挂断

### ISSUE THREAD

**Issue by dumingying** [wildfirechat/vue-pc-chat#301]
移动端（ios,安卓）拨打音视频通话，pc接听后， 移动端挂断，pc端有报错且无法挂断和关闭音视频界面，

**Comment by imndx** [comment]
已解决，请用更新最新 engine 文件测试

同时，iOS 和 Android 也需要更新高级版音视频 SDK
