### ISSUE TITLE
为什么PC端上传JSON，还有CSV以及Excel文件有时下载打开显示Object，显示不了内容，这是bug吗？希望官方大佬看下

### ISSUE THREAD

**Issue by wi8539** [wildfirechat/vue-pc-chat#304]
![download](https://user-images.githubusercontent.com/44495705/205432633-b4ef2945-6d2e-434b-af4a-3bd8e0dfa542.jpg)

**Comment by imndx** [comment]
是不是对象存储没有配置好？

上传其他文件呢？

**Comment by wi8539** [comment]
配置好了的，其他的没问题，他是概率性的出现，有些excel上传打开又是正常的，有些就不正常

**Comment by imndx** [comment]
出问题的文件，有什么特殊的吗？某些文件能必现不？

**Comment by wi8539** [comment]
能的

**Comment by imndx** [comment]
能否给我们提供一个能必现的文件？我们测试下

**Comment by wi8539** [comment]
ok

**Comment by wi8539** [comment]
这时又难复现了，等我有复现的发你
