### ISSUE TITLE
功能库参数是在哪个文件修改的

### ISSUE THREAD

**Issue by Taylor0404** [wildfirechat/vue-pc-chat#315]

**Comment by imndx** [comment]
PC SDK 是付费组件，不能直接修改 PC SDK 所绑定的地址，需要申请试用或购买才能修改所绑定的 IM 服务地址

申请试用，请看[这儿](https://docs.wildfirechat.cn/trial/)

**Comment by Taylor0404** [comment]
> 
好的，谢谢
