### ISSUE TITLE
没接通的音视频通话消息一直是【未读】状态

### ISSUE THREAD

**Issue by zxm0613** [wildfirechat/vue-pc-chat#318]
<img width="220" alt="image" src="https://user-images.githubusercontent.com/81342340/208625347-40ec187e-de15-4c9f-ba7c-3b230e44729c.png">

**Comment by imndx** [comment]
Demo 上，我们复现不了呀

**Comment by zxm0613** [comment]
我在 demo 上也复现了
<img width="240" alt="image" src="https://user-images.githubusercontent.com/81342340/209262412-0ca8b452-692b-41c8-a938-f34b9e9b4f97.png">
![image](https://user-images.githubusercontent.com/81342340/209262456-bcaf8ac9-34ec-40c2-b3cd-0d54cdebcaf4.png)

**Comment by imndx** [comment]
由于已读回执是针对会话的，不是针对具体的消息，目前需要进入会话，才会更新该会话的已读回执信息。

收到音视频邀请时，如果没有处于该会话的会话界面，那么就不会触发更新已读回执信息。


有个办法是：

音视频通话消息，不显示消息回执，只显示该通话邀请的接听状态等。

**Comment by zxm0613** [comment]
目前表现是，进入会话也不会更新音视频通话的阅读状态，得发送其他消息、对方查看后该会话才会变为已读。

**Comment by zxm0613** [comment]
目前表现是，进入会话也不会更新音视频通话的阅读状态，得发送其他消息、对方查看后该会话才会变为已读。

**Comment by imndx** [comment]
> 目前表现是，进入会话也不会更新音视频通话的阅读状态，得发送其他消息、对方查看后该会话才会变为已读。

请截图看下

**Comment by zxm0613** [comment]
上面那个截图就是，对方已经点进会话里了，但是音视频通话的阅读状态不更新。
