### ISSUE TITLE
聊天页面偶尔会出现名片样式异常

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#319]
![MTAwMDAwMDAwMDAwMDI3Nw-3D-3D-1-1671690595-P1kAlMiG2Kb7](https://user-images.githubusercontent.com/72648453/209074033-66c55145-1c7c-4796-b818-9a3216811e28.jpg)

**Comment by imndx** [comment]
出现的时候，控制台有什么报错吗？

**Comment by csd96** [comment]
偶现的 我在观察一下  这种情况出现后切换一下聊天界面就恢复正常了
