### ISSUE TITLE
当拖过来是base64的图片显示一直发送不成功，能在发送之前，构建发送的图片消息的时候把这类图片处理下吗？

### ISSUE THREAD

**Issue by wi8539** [wildfirechat/vue-pc-chat#320]
![微信图片_20221227141154](https://user-images.githubusercontent.com/44495705/209620074-ceecdadb-1856-45eb-b866-7182c57d3f6a.png)

**Comment by wi8539** [comment]
![微信图片_20221227142256](https://user-images.githubusercontent.com/44495705/209621212-743df4eb-eec7-406a-a7ea-dab89d6fb569.png)

这种替换了也没有用，希望官方大佬处理下

**Comment by imndx** [comment]
请看下 pc 端控制日志，应当能看出为什么会发送失败

**Comment by wi8539** [comment]
base64的时候，不能包含头部，你看下 imagemessagecontent.js 里面的注释，但是我们替换了还是不行，你们再看下吧

**Comment by wi8539** [comment]
![微信图片_20221227155250](https://user-images.githubusercontent.com/44495705/209631889-2d6be851-34e8-48e7-af54-f665090e2e13.png)


很多地方写死了这个，有些图片格式是data:image/png;base64,的

**Comment by imndx** [comment]
> ![微信图片_20221227142256](https://user-images.githubusercontent.com/44495705/209621212-743df4eb-eec7-406a-a7ea-dab89d6fb569.png)
> 
> 这种替换了也没有用，希望官方大佬处理下

这儿构造的```imageMessageContent```不对，```imageMessageContent```接受三个参数，分别是```fileOrLocalPath, remotePath, thumbnail```

你需要将你的 ```base64``` 数据，转成```Blob```，让后给第一个参数，第二个参数置为```null```，第三个参数表示缩略图，缩略图是```base64```格式（不包含头部），但缩略图有大小要求，不能把原始图片直接放进去，可以不转，置为```''```。

**Comment by wi8539** [comment]
必须要把base64的图片转为blob的吗？才能正常是吗？

**Comment by wi8539** [comment]
那大佬能改下吗

**Comment by wi8539** [comment]
> 
按照你的说明改了，还是不行，麻烦大佬们解决下，谢谢了

**Comment by imndx** [comment]
> > 
> 
> 按照你的说明改了，还是不行，麻烦大佬们解决下，谢谢了

我们这边没有复现这个问题的条件。

你是怎么改的，然后控制台日志出错日志是什么？

**Comment by imndx** [comment]
另外，你们用的文件存储是什么？内置的，七牛，还是野火专业存储？

**Comment by imndx** [comment]
> 另外，你们用的文件存储是什么？内置的，七牛，还是野火专业存储？

如果是用内置文件存储的话，需要先保存成临时文件，然后构造```imageMessageContent```时，将临时文件的路径放到第一个参数。

**Comment by wi8539** [comment]
我们用的七牛

**Comment by wi8539** [comment]
> > > 
> > 
> > 
> > 按照你的说明改了，还是不行，麻烦大佬们解决下，谢谢了
> 
> 我们这边没有复现这个问题的条件。
> 
> 你是怎么改的，然后控制台日志出错日志是什么？

你弄一个base64的图片拖进去野火IM就可以复现了

**Comment by wi8539** [comment]
![Z3lncW13czJr-1-1672150254-cjOFRFdqrSLH](https://user-images.githubusercontent.com/44495705/209678677-83fc6dae-611f-483b-9d9d-205079b647db.jpg)


还有就是你们的这个都拖不了base64的图片，我们自己的倒是可以

**Comment by wi8539** [comment]
回车发送了，没反应

**Comment by imndx** [comment]
可以参考如下测试代码：
```

            let base64Img = 'data:image/png;base64,iVBORw0KGgoAAAANSU.................'; // 这个是不完整的
            let b64Res = await fetch(base64Img);
            const blob = await b64Res.blob();
            let file = new File([blob], new Date().getTime() + ".jpg")
            let content = new ImageMessageContent(file, '', '')
            let conversation = new Conversation(ConversationType.Single, 'FireRobot', 0);
            wfc.sendConversationMessage(conversation, content);

```

**Comment by wi8539** [comment]
> 回车发送了，没反应

更新了代码，还是拖不了base64的图片啊

**Comment by wi8539** [comment]
可以了

**Comment by imndx** [comment]
> 可以参考如下测试代码：
> ```
> 
>             let base64Img = 'data:image/png;base64,iVBORw0KGgoAAAANSU.................'; // 这个是不完整的
>             let b64Res = await fetch(base64Img);
>             const blob = await b64Res.blob();
>             let file = new File([blob], new Date().getTime() + ".jpg")
>             let content = new ImageMessageContent(file, '', '')
>             let conversation = new Conversation(ConversationType.Single, 'FireRobot', 0);
>             wfc.sendConversationMessage(conversation, content);
> 
> ```

请先用这个测试代码进行测试下

**Comment by imndx** [comment]
> 可以参考如下测试代码：
> 
> ```
> 
>             let base64Img = 'data:image/png;base64,iVBORw0KGgoAAAANSU.................'; // 这个是不完整的
>             let b64Res = await fetch(base64Img);
>             const blob = await b64Res.blob();
>             let file = new File([blob], new Date().getTime() + ".jpg")
>             let content = new ImageMessageContent(file, '', '')
>             let conversation = new Conversation(ConversationType.Single, 'FireRobot', 0);
>             wfc.sendConversationMessage(conversation, content);
> ```
