### ISSUE TITLE
会议观众模式下，我断开网络连接几秒钟后再连接网络，有几率出现拉不到其他参会用户流的情况，这个时候收不到流的用户关闭并重新打开麦克风，我就能重新拉取到流了。

### ISSUE THREAD

**Issue by zhaoxinmeiX** [wildfirechat/vue-pc-chat#324]
断网并联网时控制台日志：
<img width="784" alt="image" src="https://user-images.githubusercontent.com/81342340/210690182-5b7e16f5-09b5-4ebc-9299-5f45cc697ea9.png">
收不到流的用户关麦并开麦时我这边的日志：
<img width="794" alt="image" src="https://user-images.githubusercontent.com/81342340/210690299-309c7911-af18-4145-a11b-04b50c3c8829.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/81342340/210690361-0541431f-80bd-4a35-b12c-4e39eaa571f5.png">

**Comment by imndx** [comment]
其他参与者是你断网期间加入的？

**Comment by zxm0613** [comment]
其他参与者是断网之前加入的，如果开了摄像头的话就显示黑屏

**Comment by imndx** [comment]
已解决
