### ISSUE TITLE
会议中，选择窗口并共享ppt文件后， 采用幻灯片播放ppt时，无法捕捉到幻灯片内容

### ISSUE THREAD

**Issue by dumingying** [wildfirechat/vue-pc-chat#326]
1、共享选择窗口，ppt文件（正常模式打开）
2、点击幻灯片播放ppt (成员看到的共享内容是停留在播放前的画面，且无内容更新)

**Comment by imndx** [comment]
你开始播放幻灯片之后，在选择播放幻灯片的窗口进行屏幕共享呢？

**Comment by imndx** [comment]
这个有个相关问题：https://bugs.chromium.org/p/webrtc/issues/detail?id=3852

**Comment by imndx** [comment]
> 这儿有个相关问题：https://bugs.chromium.org/p/webrtc/issues/detail?id=3852

简单说，这个问题，可能无解

开始播放幻灯片的时候，是打开了一个新的窗口，而不是在原来的窗口，如果屏幕共享的时候，选择了原来的窗口，那么就捕获不到新窗口的内容

**Comment by dumingying** [comment]
嗯嗯 ，好的，&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/vue-pc-chat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月12日(星期四) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wildfirechat/vue-pc-chat] 会议中，选择窗口并共享ppt文件后， 采用幻灯片播放ppt时，无法捕捉到幻灯片内容 (Issue #326)





  
这儿有个相关问题：https://bugs.chromium.org/p/webrtc/issues/detail?id=3852
  
简单说，这个问题，可能无解
 
开始播放幻灯片的时候，是打开了一个新的窗口，而不是在原来的窗口，如果屏幕共享的时候，选择了原来的窗口，那么就捕获不到新窗口的内容
