### ISSUE TITLE
是否支持 龙芯 mips 和 loongarch64？

### ISSUE THREAD

**Issue by xupea** [wildfirechat/vue-pc-chat#338]

**Comment by imndx** [comment]
支持的

**Comment by xupea** [comment]
@imndx 有提供 mips64el 和 loongarch64 的 electron 吗？龙芯的好像没法交叉编译呢

**Comment by imndx** [comment]
龙芯版的 electron 可以从他们的开源社区下载，如果需要 龙芯版 野火IM `PC SDK`，请看下[这儿](https://docs.wildfirechat.cn/trial/)
