### ISSUE TITLE
消息数同步

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#353]
是否有获取本地消息同步数和远程消息总数的接口(针对单个会话)

**Comment by heavyrain2012** [comment]
没有明白什么意思，请详细描述一下

**Comment by csd96** [comment]
场景: 一台新的机子下载客户端，初次拉取1000条聊天记录(对于某个会话可能未拉取完整的历史聊天记录)，需要看出某个会话是否已经拉取了所有远程历史记录及与本地记录的差值。
期望: 
1、针对某个会话可以知道这个会话的远程历史记录一共有多少条
2、针对某个会话可以知道这个会话的本地记录一共有多少条

**Comment by heavyrain2012** [comment]
目前没有这两个接口。请问这是什么场景下需要用到这两个方法

**Comment by csd96** [comment]
因为聊天记录搜索走的是本地，要先手动加载后(上滑从远程拉取)才能进行搜索，如果有查看本地记录与历史记录的差值及选择性拉取历史记录的接口，就可以一键同步聊天记录进行聊天记录搜索。

**Comment by heavyrain2012** [comment]
没有办法来获取本地和服务器的差值。实际上搜索应该分本地搜索和服务器搜索，本地只能保存有效的消息，用户可以去服务器搜索所有历史消息。服务器上默认最长消息保存时间是3年，可能很多单位要求保留更长时间甚至是永久保存。所以需要你们开发搜索服务，定时把数据同步到搜索服务，然后客户端来这个搜索服务来搜索消息。
