### ISSUE TITLE
当前会话无聊天记录，及对端未发送消息的情况下，标记未读失败

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#354]
![0494d54a142d81b63c93138a377aa87](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/e5acd827-4ad9-4d6d-8531-f1cfbcc5f976)
触发标记未读方法中的msgUid为'0'，导致无法发送新消息

请参考企业微信，在无聊天记录的情况下，仍能标记未读
![fab0ad5dd746667a31f0144e0ad25fc](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/c1098ca2-e4ec-4742-b5ab-5e007cf09dcd)

**Comment by heavyrain2012** [comment]
现在的实现办法是找到一个最近的收的消息，把消息改成未读，如果没有消息就没有办法标记未读了

**Comment by heavyrain2012** [comment]
可以在弹出菜单前检查，有没有收到的消息，如果没有收到的消息就不显示标记未读的菜单
