### ISSUE TITLE
聊天记录根据时间段查询

### ISSUE THREAD

**Issue by gushuting123** [wildfirechat/vue-pc-chat#356]
如题，查询历史聊天记录，可以传 开始时间和结束时间，查询这个时间段内的聊天记录
uniapp插件 和 web sdk同时需要这个接口

**Comment by heavyrain2012** [comment]
在uniapp客户端，调用这个方法来根据时间获取消息 getMessagesByTimestampV2

在web端，因为web端本地消息只有非常少的消息同步到本地，因此没有办法在web端根据时间获取本地消息。有个办法是使用获取远程消息的接口，这个接口有个参数是消息uid，服务器根据这个参数做为消息的起始点，可以有个方法把时间转换成消息id，计算公式是: （时间的毫秒数 - 1514736000000L）右移21位，详情可以参考社区版IM服务的MessageShardingUtil类的getMsgIdFromTimestamp函数
