### ISSUE TITLE
本地聊天数据拉取缺失

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#357]
![MTAwMDAwMDAwMDAwMDAwMQ-3D-3D-1-1684295097-P1kAlMiG2Kb7](https://github.com/wildfirechat/vue-pc-chat/assets/72648453/2482bfd8-88de-4097-8952-7aabbeb18e09)

**Comment by imndx** [comment]
没看明白，请详细说明

**Comment by csd96** [comment]
let lmsgs = wfc.getMessages(conversation, conversationState.currentConversationOldestMessageId, true, 20);
这个接口拉取的聊天记录有缺失
 wfc.loadRemoteConversationMessages 则不会

**Comment by heavyrain2012** [comment]
最新版本已经解决，请联系我们更新版本
