### ISSUE TITLE
如何自定义文件上传逻辑

### ISSUE THREAD

**Issue by JoyLau** [wildfirechat/vue-pc-chat#358]
想修改发送文件的逻辑，上传到我们自己的文件服务器上， 然后再回带一个地址回来通过消息发出去， 应该修改源码的哪个地方？

**Comment by imndx** [comment]
下面是发送文件的的问题，可以在此修改

https://github.com/wildfirechat/vue-pc-chat/blob/db713dcb8897551e59ad7f28a4687ca0c9d2cef3/src/store.js#L1060-L1070

可以参考下面的代码进行修改，但不能直接修改`proto.min.js`文件，不然会导致后续没办法合并我们的更新：

https://github.com/wildfirechat/vue-pc-chat/blob/db713dcb8897551e59ad7f28a4687ca0c9d2cef3/src/wfc/proto/proto.min.js#L1850-L1870
