### ISSUE TITLE
桌面端调用getMessagesEx2V2报错

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#365]
![59a993f51b92953477f9540393b36c8](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/6b3604a1-f9b6-4e64-8636-115004643e17)

![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/1954c6b9-045c-402f-a89c-688a7ada6965)

**Comment by imndx** [comment]
这个 api 是新加的，请联系我们更新 SDK
