### ISSUE TITLE
发送媒体文件，文件上传后才能触发sendMsg事件

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#366]
发送的媒体文件，等发送成功后，才会触发监听sendMsg事件。

**Comment by dengxueru** [comment]
使用了修改代码，但是这样会触发两次sendMsg，立即发送一次，成功后仍会触发一次
![f94a42dc9550a8bdf487e5e829d7c41](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/54ee5f65-024c-4dcb-a120-c45d0ea3b808)

上图代码是不是应该需要注释掉？

**Comment by imndx** [comment]
> 使用了修改代码，但是这样会触发两次sendMsg，立即发送一次，成功后仍会触发一次 ![f94a42dc9550a8bdf487e5e829d7c41](https://user-images.githubusercontent.com/38432260/241611001-54ee5f65-024c-4dcb-a120-c45d0ea3b808.png)
> 
> 上图代码是不是应该需要注释掉？

不用注释掉，注释掉之后，发送普通消息，就会收不到发送消息事件。

现在发送大文件时，会触发两次`发送消息`的事件通知，但上层已经做了处理。
