### ISSUE TITLE
关于消息已读

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#368]
场景：A给B一次性发了很多消息，B只点击了一下与A的会话，只已读了第一屏下的消息，但在A的视角之前发的所有消息全部变成已读状态。
问题: 有些会话内的消息其实没有已读，却显示已读状态
期望:从 ReadEntry 类来看 似乎已读消息这块是从整个会话来判断的，是否能够更细致的体现某条消息已读，在ReadEntry里返回对应的MessageId

**Comment by imndx** [comment]
现在不支持具体消息的已读/未读状态，只支持会话级别，读到了什么时间点。
