### ISSUE TITLE
消息字段中会话target的意义

### ISSUE THREAD

**Issue by sjhgithub** [wildfirechat/vue-pc-chat#375]
似乎Single类型的会话,target不同于其它类型,会单独处理,目前不知道该字段的意义
[接收方]接收到的该消息,sender(from)      等于conversation.target;
[发送方]接收到的该消息,sender(from)[不]等于conversation.target
不明白该conversation.target的意义所在,望指教
另外跟开发文档说明貌似不一致:
https://docs.wildfirechat.cn/base_knowledge/conversation.html#%E4%BC%9A%E8%AF%9D%E7%9B%AE%E6%A0%87target%EF%BC%9A
跟会话类型不同而不同，Single类型时，目标为对方用户Id；Group类型时，目标为群Id；Chatroom类型时，目标为聊天室Id；Channel类型时 目标为Channel ID。

**Comment by imndx** [comment]
就是文档上的解释

单聊时，会话的另一方的uid

**Comment by sjhgithub** [comment]
> 就是文档上的解释
> 
> 单聊时，会话的另一方的uid

但是实际上,接收方收到的消息并不是,sender(from) 会等于conversation.target

**Comment by imndx** [comment]
> > 就是文档上的解释
> > 单聊时，会话的另一方的uid
> 
> 但是实际上,接收方收到的消息并不是,sender(from) 会等于conversation.target

`sender === conversation.target` 这就是表示会话的对方的 `uid` 是`conversation.target`

**Comment by sjhgithub** [comment]
> 

也就是单聊时，同一消息,接收方的conversation.target与该消息的发送方的conversation.target,不一样,对吧

**Comment by sjhgithub** [comment]
也就是说conversation.target并不是相对于该消息而言,而是相对于得到该消息的id而言的

**Comment by imndx** [comment]
> 也就是说conversation.target并不是相对于该消息而言,而是相对于得到该消息的id而言的

是的，单聊时，`conversation.target`不一定是消息的发送者，因为消息可能是自己发送的。
