### ISSUE TITLE
替换新的音视频文件后，会议中开关视频后，再开关麦克风自己头像也会变黑

### ISSUE THREAD

**Issue by dumingying** [wildfirechat/vue-pc-chat#377]

**Comment by imndx** [comment]
demo 上可以复现吗？

**Comment by dumingying** [comment]
可以的，

**Comment by dumingying** [comment]
demo 上有这个报错
![截屏2023-06-28 下午5 06 25](https://github.com/wildfirechat/vue-pc-chat/assets/37329222/f91fd6be-682a-4820-a49a-093a50b4879b)

**Comment by imndx** [comment]
> demo 上有这个报错 ![截屏2023-06-28 下午5 06 25](https://user-images.githubusercontent.com/37329222/249415277-f91fd6be-682a-4820-a49a-093a50b4879b.png)

这个报错不影响
