### ISSUE TITLE
合并类型中的消息，content返回是一个空对象

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#382]
![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/6d8d92bc-19e4-4073-916a-c3eeef79cf50)

期望至少出现content中的content

**Comment by imndx** [comment]
不该用content，这个是内部使用的，用messageContent字段

**Comment by dengxueru** [comment]
> 不该用content，这个是内部使用的，用messageContent字段

在图片消息类型中，我们把图片的宽高放到了content中的content   如下图
![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/1e46f821-aaed-4c62-931b-0996e623b372)

那么在合并消息中拿不到图片的宽高

**Comment by imndx** [comment]
你看messageContent字段里面有吗？

**Comment by dengxueru** [comment]
> 你看messageContent字段里面有吗？

messageContent中的content没有任何值，但是我更新了最新的SDK，有了imageWidth和imageHeight。

我尝试用包含imageWidth和imageHeight创建一个图片消息，发出去的消息中，imageWidth和imageHeight都为undefined

**Comment by dengxueru** [comment]
使用最新版的SDK中的imageWidth和imageHeight

已经解决合并消息中的图片尺寸问题
