### ISSUE TITLE
移动app(安卓)群聊中@桌面端(win)人员，unreadMention为0

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#383]
在测试环境中
移动app(安卓)群聊中@桌面端(win)人员，unreadMention为0

同样的SDK，同样的操作正式环境中是正常的，排除移动和桌面SDK问题

区别就是之前IM SERVER版本不一样

测试环境版本
![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/ecdb63c5-4511-4141-8d4e-2f948acec729)

**Comment by imndx** [comment]
正式环境的版本信息是什么？

**Comment by heavyrain2012** [comment]
在测试环境中
移动app(安卓)群聊中@桌面端(win)人员，unreadMention为0

在测试环境中，app @ app人员，桌面@桌面人员是什么情况？

**Comment by dengxueru** [comment]
> 正式环境`im-server`的版本信息是什么？

正式环境的版本比较老
![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/49185b1f-6ecd-4570-a9ef-f7b162df47df)

**Comment by dengxueru** [comment]
移动app反复测试后，发现设置@时，@设置问题
