### ISSUE TITLE
群聊中，发送合并消息(包含大量图片消息)，设置toUsers，无效

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#384]
在群聊中，发送合并消息(包含大量图片，会触发合并消息上传)

发送消息sendMessage中的toUsers，设置群内的某一个人，仍会发送至群内所有人

**Comment by heavyrain2012** [comment]
任何消息发送的时候都会先encode为messagePayload，然后再发送这个payload。请debug看一下，组合消息encode为payload时，这个payload里是不是有toUsers

**Comment by heavyrain2012** [comment]
其他消息，比如文本消息，发送定向消息是对的吗？

**Comment by dengxueru** [comment]
> 其他消息，比如文本消息，发送定向消息是对的吗？

如果合并消息不触发上传，toUsers是有效的。其他消息目前没有测试

**Comment by dengxueru** [comment]
发送合并消息(包含大量图片消息)，设置toUsers如果是多个人，toUsers里面的人无法接收到消息

如果toUsers是一个人，是对的
