### ISSUE TITLE
当前设备无摄像头和麦克风，会议会断开(demo必现)

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#386]
当前设备无摄像头，无麦克风
1、进入会议后，打开摄像头或麦克风或屏幕共享，导致会议断开

前端通过以下方法做容错，限制不住
DetectRTC.hasMicrophone
DetectRTC.hasWebcam
如果麦克风驱动有问题，打开麦克风依旧会断开会议

**Comment by imndx** [comment]
当设备没有摄像头、麦克风时，可以限制直接不让进入会议，可以看下`avenginekitproxy.js`
