### ISSUE TITLE
期望新增一个图文混合媒体消息

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#392]
类似企业微信中的图文混合消息

编辑器内增加图片和文字
![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/054c5ce2-5f60-452f-b9e5-8dc76ed22a75)

图片和文字发送后变成一条消息
![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/558d69af-2717-4a32-862c-ca585e2bfc5a)

可以下载企业微信试试

**Comment by imndx** [comment]
用 mac 版本企业微信测试了下，是分开发送的，比如编辑框里面有两张图、一段文字，发出去是 3 条消息。

**Comment by dengxueru** [comment]
> 用 mac 版本企业微信测试了下，是分开发送的，比如编辑框里面有两张图、一段文字，发出去是 3 条消息。

是的，在win下才会有图文混合

我们业务需求中需要这种类型消息

我们已完成自定义图文类型消息，但是效果不理想，没有底层SDK效果好

不好在两个地方
1、使用下图上传媒体文件方法会很容易上传失败，容易卡慢(正式环境下)
2、图文类型消息，需要等待所有图片上传结束，才能发送自定义消息。如果上传图片的过程中，切换了会话列表，就容易导致消息丢失，如果是SDK消息就不会丢失(或者这种有什么比较好的方法处理)。
![796895032d27f356c9c855c9222ae39](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/13af7da9-28e0-421b-b301-ba2cab552528)

**Comment by imndx** [comment]
可以先发送合并转发消息一样，先`insertMessage`，等媒体文件上传成功之后`updateMessageContent`，等所有媒体文件都上传成功了，再进行发送

容易上传失败的问题，需要查下：
1. 配置的对象存储是什么？
2. 失败的时候，有什么日志等
