### ISSUE TITLE
insertMessage方法返回mentionedType和mentionedTargets异常

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#393]
![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/d68c7b16-e5c8-4bd5-9014-c80de95e85d7)

步骤
创建带有【@人员】的messageContent消息体
insertMessage方法插入本地返结果的消息体中，mentionedType和mentionedTargets被重置

**Comment by heavyrain2012** [comment]
客户端协议栈的问题，已经解决，请更新解决
