### ISSUE TITLE
撤回信息里面缺少originalBinaryContent

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#394]
![781595a320ab8221a2e57b869f532a9](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/6d64f459-c31d-4cba-87ef-a971077fd0ed)

一个消息体中extraContent中包含信息，撤回信息里面extraContent就找不到了

**Comment by heavyrain2012** [comment]
这个问题已经解决，需要升级IM服务和客户端协议栈，请更新后验证
