### ISSUE TITLE
建议：能不能把野火相关的文件整合到一个文件夹中，这样方便区分业务代码和野火

### ISSUE THREAD

**Issue by w3cways** [wildfirechat/vue-pc-chat#396]
/scripts目录
marswrapper.node文件
src/wfc
src/config.js
src/platform.js
诸如此类文件、文件夹整合到一个目录里

**Comment by imndx** [comment]
如果全部用相对路径来引用的，是不是你们就可以随便放任何地方了？

**Comment by w3cways** [comment]
> 如果全部用相对路径来引用的，是不是你们就可以随便放任何地方了？

要的就是这个效果哇，现在野火相关的文件分散在各个地方，换个框架啥的 ，改动起来比较麻烦

**Comment by w3cways** [comment]
> 如果全部用相对路径来引用的，是不是你们就可以随便放任何地方了？

..是把野火相关的文件，都整合到一个文件夹里，不是把.../ 改写成 @/

例如

wfcPlugin
├─ scripts目录
├─ marswrapper.node文件
├─ wfc文件夹
├─ config.js
├─ platform.js
├─ ...
├─ ...

**Comment by imndx** [comment]
如果你们在 demo 的基础上改动很大的话，这么做是有意义的，但大部分客户改动都挺小的。如果这样子设计目录结构，对他们来说，就不太友好了。

现在我们相关代码，之间的引用，都改成了相对路径，要改成你说的这种结构很简单了，基本只需要建个目录，然后把这些目录都拖进去即可。



> > 如果全部用相对路径来引用的，是不是你们就可以随便放任何地方了？
> 
> ..是把野火相关的文件，都整合到一个文件夹里，不是把.../ 改写成 @/
> 
> 例如
> 
> wfcPlugin ├─ scripts目录 ├─ marswrapper.node文件 ├─ wfc文件夹 ├─ config.js ├─ platform.js ├─ ... ├─ ...
