### ISSUE TITLE
关于搜索

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#398]
根据部分英文聊天记录的关键字进行搜索

**Comment by heavyrain2012** [comment]
我们做了一下修改，可以匹配开头的字符，比如“hello world", he 和 wor 都是可以匹配的，但ll和rld就不行，这样应该可以了吧

**Comment by heavyrain2012** [comment]
如果要是匹配中间的，会造成数据库太大，匹配开头应该就可以了

**Comment by csd96** [comment]
是否可以做一个配置来开启 和 关闭 这个单字检索 我们来做取舍 是匹配开头字符还是匹配全部的单个字符
