### ISSUE TITLE
关于好友请求

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#399]
好友申请可以多次请求然后显示最新一次请求的信息吗?

**Comment by heavyrain2012** [comment]
现在是禁止多次情况，这样做的原因是为了方式骚扰，可以改成请求后5分钟内可以再次请求，超过就不允许了。请等我们排期处理

**Comment by heavyrain2012** [comment]
IM服务已经处理，专业版请联系我们更新版本

**Comment by csd96** [comment]
在五分钟内,请求发送成功后、接收方未接收到最新的好友请求更新回调，
在通过好友请求后，好友申请的文本信息会刷新成最新的

**Comment by heavyrain2012** [comment]
IM服务处理的问题，没有更新请求的时间导致没有同步下来，请更新最新的版本
