### ISSUE TITLE
GPU process crashes with exit code -1073741515

### ISSUE THREAD

**Issue by imndx** [wildfirechat/vue-pc-chat#406]
启动参数加上：`--in-process-gpu`

FYI: https://github.com/electron/electron/issues/37862

**Comment by a170906063a** [comment]
这个怎么在开发中的代码中加入呀？

**Comment by imndx** [comment]
https://github.com/wildfirechat/vue-pc-chat/blob/c92f1b94fc84064f2c96981bdb4e3d3334cbcac7/src/background.js#L65

类似这种

**Comment by a170906063a** [comment]
谢谢，不需要做类似环境判断这种吗？我看这个错误好像只有部分电脑会触发

**Comment by a170906063a** [comment]
而且我看问题里面说稳定版已经解决了，但是我用了29.1.6版本的好像还是有这个问题
