### ISSUE TITLE
占用系统内存后过高后一直不会释放

### ISSUE THREAD

**Issue by xiezefeng0927** [wildfirechat/vue-pc-chat#410]
1、在消息接收或者发送评率很高的情况下(1-10秒内)，接收到图片消息并滑动查看消息时，内存会瞬间的成倍数增长，且不会释放
2、不断的切换聊天人员(私聊或者群聊)，内存也会不断增长且不释放
等等多种情况下高内存占用且不释放

**Comment by imndx** [comment]
你好，我们在 mac 上测试并没有复现你说的内存泄漏情况。

请确认：
1. 你们是在什么系统测试？
2. 是否是最新代码？
3. 什么都不修改，直接用 demo 测试，能否复现？

如果用 demo 能直接复现，请详细描述复现步骤，并附上泄漏截图和`snapshot`文件，以便我们分析

**Comment by imndx** [comment]
no response
