### ISSUE TITLE
搜索带有特殊符号的消息，无法搜索到该消息

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#417]
**问题一**
我使用的SDK为searchConversationEx及searchMessageEx，将带有特殊字符(192.168.0.0 / 160万吨/年树脂项目共摊等)传入字段keyword，无法搜索到该消息。

我使用官方Demo 复现，官方demo使用的是searchConversation。
![image](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/a4a40504-9424-4cad-adfc-308239ce120f)
![5e735c7aa0d90bd8b71f38d9d864de9](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/37b44476-5647-4a91-ba98-0525df8c50a8)

问题二
搜索英文单词无法模糊搜索，必须要全拼才能搜索出

比如：搜索asdasd，传入asd字符，无法搜索出消息，必须传入asdasd才能搜索出

**Comment by heavyrain2012** [comment]
问题2更新SDK可以解决问题。问题1我们查查

**Comment by heavyrain2012** [comment]
node文件

**Comment by heavyrain2012** [comment]
> 问题2更新SDK可以解决问题。问题1我们查查

问题1也解决了，也是协议栈的问题，请联系我们更新

**Comment by dengxueru** [comment]
> > 问题2更新SDK可以解决问题。问题1我们查查
> 
> 问题1也解决了，也是协议栈的问题，请联系我们更新

只需要更新node文件，对吧。

**Comment by imndx** [comment]
是的
