### ISSUE TITLE
quitGroup退群之后，通过本地搜索群组searchGroupsapi搜索群聊仍能搜到

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#418]
问题一
quitGroup桌面端主动退群之后，通过本地搜索群组searchGroupsapi搜索群聊仍能搜到

问题二
桌面端用户主动退群成功后，再次主动退群，桌面端会重复收到退群消息，移动端不会收到消息，SDK可以限制(这个问题也可以在UI层，限制退出群聊按钮)

**Comment by heavyrain2012** [comment]
问题一
quitGroup桌面端主动退群之后，通过本地搜索群组searchGroupsapi搜索群聊仍能搜到
 
这个是搜索的群名称还是群成员的名称？

问题二
桌面端用户主动退群成功后，再次主动退群，桌面端会重复收到退群消息，移动端不会收到消息，SDK可以限制(这个问题也可以在UI层，限制退出群聊按钮)
可以在UI处理，当退出成功后删除本地会话，退出会话的UI @imndx

**Comment by imndx** [comment]
@heavyrain2012 

`quitGroup`之后，通过`searchGroup(群名称)`还能搜到，`matchType`是 2

**Comment by dengxueru** [comment]
> @dengxueru
> 
> 退群之后，UI 上已经看不到这个群了，怎么再次退群？

建议是再次触发退群的时候，桌面端不要收到重复退群的消息，这个地方限制一下。
