### ISSUE TITLE
会话列表头上的用户搜索

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#419]
![20231204161939629](https://github.com/wildfirechat/vue-pc-chat/assets/72648453/11dbc1fd-5a25-4c23-b487-02b7c2c767d4)
![20231204162006802](https://github.com/wildfirechat/vue-pc-chat/assets/72648453/80306cbf-b5fb-4dc6-8dd2-77a3d111cb21)

wfc.searchUser() 当searchKey是空格 或者 % 也会搜索出一些人来

**Comment by imndx** [comment]
`%`也能搜索的问题，请联系我们更新`pc sdk`

**Comment by csd96** [comment]
这是更新windows sdk就好 还是 服务也要




1178584616
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/vue-pc-chat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wildfirechat/vue-pc-chat] 会话列表头上的用户搜索 (Issue #419)





 
%也能搜索的问题，请联系我们更新pc sdk

**Comment by imndx** [comment]
> 这是更新windows sdk就好 还是 服务也要 1178584616 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wildfirechat/vue-pc-chat" ***@***.***&gt;; 发送时间:&nbsp;2023年12月5日(星期二) 中午11:07 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wildfirechat/vue-pc-chat] 会话列表头上的用户搜索 (Issue #419) %也能搜索的问题，请联系我们更新pc sdk — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

windows

**Comment by csd96** [comment]
昨天替换了新的sdk 问题还在 %还是能搜索

**Comment by heavyrain2012** [comment]
这个是IM服务的问题，已经解决，请更新最新版本

**Comment by csd96** [comment]
60.0.0.21 端口号37372 Windows PC SDK
公司:中宏立达
