### ISSUE TITLE
通讯录头部搜索的搜索结果

### ISSUE THREAD

**Issue by csd96** [wildfirechat/vue-pc-chat#422]
1.点击搜索结果中的会话
2.页面跳转到对应会话、会话列表位置不变
期望:像wx一样会把会话位置移至会话列表头部

有尝试使用wfc.setConversationTimestamp()更新会话时间戳达到位置调整的效果但是_reloadConversation后会被还原

**Comment by imndx** [comment]
`wfc.setConversationTimestamp` 设置当前时间`new Date().getTime()`是没问题的。
