### ISSUE TITLE
searchConversationEx，这个搜索历史聊天记录的方法搜索搜索部分词汇，返回为空(偶发)

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#423]
用户搜索使用了一段时间之后，搜索部分词汇返回为空，但是该词汇在聊天消息中存在的。如果断开重连IM后，再次搜索正常。
我分别看了两个人的数据库为159M和89M

**Comment by heavyrain2012** [comment]
有没有可能是出现问题的时候，没有调用connect？可以在出现问题时发送消息，看看对方能不能收到
