### ISSUE TITLE
使用非‘/’路由path登录,导致聊天界面无法收发消息

### ISSUE THREAD

**Issue by zjcadiq** [wildfirechat/vue-pc-chat#424]
在使用 非 ‘/’ 路由页面登录后，能登录成功，但是消息都发不出去
野火demo也存在该现象
具体复现代码如下

![20631709003663_ pic](https://github.com/wildfirechat/vue-pc-chat/assets/99380022/70ad86a9-e246-48dc-adb3-99d6dad1c9a9)

![20641709003679_ pic](https://github.com/wildfirechat/vue-pc-chat/assets/99380022/35f29ada-967c-4630-9e53-6d5dfaf926c2)

**Comment by imndx** [comment]
由于是多窗口应用，不需要在每个窗口都进行一次初始化，故采用了一些条件判断当前窗口是否是主窗口，仅在主窗口进行初始化操作。

判断是否是主窗口时，会根据当前窗口加载的`url`进行判断，修改了窗口启动时加载的`url`，则需要同步更新下面这部分代码的判断逻辑：

https://github.com/wildfirechat/vue-pc-chat/blob/e13bdef153e3e9d52b02535afd7c2d845e7d581d/src/main.js#L33-L40


以下是修改后的逻辑，供参考：
`if (path === '/login'/*login*/ || path.startsWith('/home') || href.indexOf('#') === -1) {`
