### ISSUE TITLE
这行改动会导致点击视频无法播放

### ISSUE THREAD

**Issue by xlsfs** [wildfirechat/vue-pc-chat#428]
https://github.com/wildfirechat/vue-pc-chat/blob/c92f1b94fc84064f2c96981bdb4e3d3334cbcac7/src/store.js#L372

这行改动会导致新发送的视频点击无法播放
消息的uid为空导致无法播放

**Comment by imndx** [comment]
怎么复现？
播放应当和 uid 没关系的

**Comment by xlsfs** [comment]
在视频还没上传完成的时候点播放就会出现，控制台输出

on show-multimedia-preview-window undefined {
  url: 'http://localhost:8080/#/mmpreview?messageUid=0',
  messageUid: { low: 0, high: 0, unsigned: false },
  size: undefined
}
create windows url http://localhost:8080/#/mmpreview?messageUid=0

**Comment by imndx** [comment]
嗯嗯，这种有可能，可以改一下，通过`messageId`去预览

**Comment by imndx** [comment]
已解决
