### ISSUE TITLE
桌面端getUnreadCount获取未读数问题

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#429]
A群聊设置免打扰，如果接收到@所有人，@人员消息
通过getUnreadCount获取总未读数会增加1
**demo总角标是通过会话列表相加得来的，不建议使用**
实际请看右侧打印的unread 并不为0
**三端，目前都有这个问题**
![46729e97426ad6842293b3d81891fdc](https://github.com/wildfirechat/vue-pc-chat/assets/38432260/c238c64b-8f31-489f-95e6-4521edf7233c)

**Comment by imndx** [comment]
<img width="1482" alt="image" src="https://github.com/wildfirechat/vue-pc-chat/assets/34434072/83b43f0d-0cc0-4ce4-b17d-57aa8eaa65b6">

demo 上无法复现呀

**Comment by dengxueru** [comment]
> <img alt="image" width="1482" src="https://private-user-images.githubusercontent.com/34434072/319108958-83b43f0d-0cc0-4ce4-b17d-57aa8eaa65b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzU0NDgsIm5iZiI6MTcxMjEzNTE0OCwicGF0aCI6Ii8zNDQzNDA3Mi8zMTkxMDg5NTgtODNiNDNmMGQtMGNjMC00Y2U0LWIxN2QtNTdhYThlYWE2NWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZWNjNjFmMzE3NTZmZDdhOWI5NzRhZWY4ZDc0NTkzMGQwNjYzNjBhNWQwZjRjZGQxYTRjMGJiOTUwYTc0N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ByLpVCWyH85K9jNHneF0ighm_ScVabeFQihR_uBR8Lo">
> demo 上无法复现呀

用别的账号
@你或者@所有人就能出现
我的描述中已经说明了

**Comment by imndx** [comment]
会话信息里面，`unreadCount` 里面是真的未读数、未读@、未读@all，但由于会话免打扰，然后就不显示未读数角标，显示了小红点


而`getUnreadCount`的时候，如果把免打扰的会话的未读数直接忽略的话，这样unreadCount 里面的意义，不同地方不太一样了

实现issue中的需求时，可以这样做：
先遍历会话列表，过滤掉免打扰的会话，自己加一下
