### ISSUE TITLE
群聊-视频/语音通话-无法加入对话

### ISSUE THREAD

**Issue by JAYCHOUMINSTER** [wildfirechat/vue-pc-chat#430]
![Snipaste_2024-04-07_14-56-24](https://github.com/wildfirechat/vue-pc-chat/assets/51279035/1bb639a8-95d0-4b03-a359-8dcf07d90f74)

**Comment by imndx** [comment]
demo 上面上能复现吗？

**Comment by JAYCHOUMINSTER** [comment]
可以复现

> demo 上面上能复现吗？

**Comment by JAYCHOUMINSTER** [comment]
> demo 上面上能复现吗？

就是拉了现有版本，替换了下接口以及proto_addon下文件。能复现
