### ISSUE TITLE
关于WPF版本的本地消息和vue版本的本地消息共用问题

### ISSUE THREAD

**Issue by jpguo520** [wildfirechat/vue-pc-chat#433]
之前咱们有一版本WPF版本的IM，现在又对接了Electron-VUE版本的IM，现在需要WPF版本的IM的历史消息数据在Electron-VUE版本的IM中加载使用，这种场景能实现吗？

我现在是将WPF版本的IM的数据文件直接复制到Electron-VUE版本的IM的文件夹下，启动后不能读取里面的消息。在退出IM后数据文件被更新了，这是需要进行进行转化以后才能使用吗，还是在这两个版本下本地消息就不能共用？

![image](https://github.com/wildfirechat/vue-pc-chat/assets/26107242/1639eaba-ecdf-4b6f-988e-c6a858c6eb02)

**Comment by imndx** [comment]
原因是`clientId`不一样，导致打不开数据库。

`wildfirechat` 目录下有个`wildfirechat`的文件，你迁移的时候，把这个文件也迁移过去，应当就好了；

但这样会导致个问题，由于新旧应用的`clientId`被强制设置为相同了，那两个应用不能同时启动，不然会互踢，或者有其他奇怪的问题。
