### ISSUE TITLE
store.getGroupMemberUserInfos 根据 MemberId 排序异常

### ISSUE THREAD

**Issue by zjcadiq** [wildfirechat/vue-pc-chat#435]
store.getGroupMemberUserInfos 根据 MemberId 排序，根据 wfc.getGroupMemberIds(groupId)获取到的MemberIds，将禁言的用户排在了群主及管理员前面。
![image](https://github.com/user-attachments/assets/6c11aa44-02f7-48cd-a6d5-15a7fd76443a)
![image](https://github.com/user-attachments/assets/b033d940-ced4-4910-8fde-58b231061cff)
![image](https://github.com/user-attachments/assets/003cd95f-c03f-486a-a616-330be6df60ac)

**Comment by heavyrain2012** [comment]
协议栈在处理排序时比较简单，只考虑到了最后修改时间。有2种办法处理，一种是这个方法是调用了获取群组成员的接口，在获取成员返回的数据做一下按类型排序，这个你们自己就可以实现。另外一种方法是等待我们修改协议栈，等修改完成后再给你们发个版本。

**Comment by heavyrain2012** [comment]
协议栈已经实现
