### ISSUE TITLE
在A聊天框输入图片后，切换到B聊天框，再返回到A聊天框时，输入的图片清空了

### ISSUE THREAD

**Issue by JinxChung** [wildfirechat/vue-pc-chat#439]
但是在B聊天框按enter健可以发送出去，发出的内容是图片的代码
<img width="553" alt="image" src="https://github.com/user-attachments/assets/abd98b52-6751-45d6-9b9d-62e01719ef9d">

**Comment by imndx** [comment]
这个 commit 也是相关的

8bc4dca
