### ISSUE TITLE
切换音频输入设备无效setAudioInputDeviceId、setInputStream

### ISSUE THREAD

**Issue by dengxueru** [wildfirechat/vue-pc-chat#442]
使用navigator.mediaDevices.enumerateDevices()获取麦克风设备ID
1、使用this.session.setAudioInputDeviceId(deviceId) 切换麦克风  无效
2、使用以下方法获取麦克风流后，使用this.session.setInputStream(stream）切换流，无效 ，流是正常的，使用<audio 标签正常。
      const stream = await navigator.mediaDevices.getUserMedia({
          audio: { deviceId: { exact: params.deviceId } },
      })
      this.session.setInputStream(stream)

**Comment by imndx** [comment]
设置进去的 `deviceId` 正确吗？

**Comment by imndx** [comment]
反馈是 未更新音视频 SDK 导致
