### ISSUE TITLE
[Help Wanted] 关于如何将消息类型改为存储类型的问题

### ISSUE THREAD

**Issue by k1nz** [wildfirechat/vue-pc-chat#443]
我想在发送远程桌面邀请以及结束时，类似视频通话和语音那样发送一条消息通知双方，该如何调整？
<img width="95" alt="image" src="https://github.com/user-attachments/assets/db38e9e6-15af-4862-a335-3cc5d3dd75f0" />

**Comment by k1nz** [comment]
<img width="972" alt="image" src="https://github.com/user-attachments/assets/aebb068a-43e7-4e40-a1b8-c9abc37c04d8" />
我尝试在 `messageConfig.js` 中修改对应的 `MessageContent` 的存储类型 flag，在接收到消息后，`messageId` 仍然为 0

**Comment by imndx** [comment]
接收方也修改了吗？双方都需要进行修改的。

针对你的需求：
1. 修改`RCInviteMessageContent(请求远程协助)`和`RCRequestMessageContent(请求远程控制)`的`persistFlag`为`persist` 或者 `persist_and_count`
2. 定义对应的 UI，这个可以参考`CallStartMessageContentView`
3. 将 UI 和消息关联，具体可以参考`MessageContentContainerView.vue`中`CallStartMessageContentView`的配置

**Comment by k1nz** [comment]
现在可以了，应该是热更新的原因导致的不生效。

---

另外，我想为 `RCRequestMessageContent` 消息加上当前的状态，但是我遇到了 共享画面接受并建立连接 的状态似乎不正确

我是这样做的：
1. 为 `RCRequestMessageContent` 添加 `status`
```diff
// rcRequestMessageContent.js
export default class RcRequestMessageContent extends MessageContent {
    callId;
    pin
    targetIds = [];
    audioOnly = false;
++    status
++    endTime
++    connectTime

    constructor(callId, pin) {
        super(MessageContentType.VOIP_REMOTE_CONTROL_REQUEST, 0, []);
        this.callId = callId;
        this.pin = pin;
    }

    digest() {
        return ''
    }

    encode() {
        let payload = super.encode();
        payload.content = this.callId;
        let obj = {
            a: this.audioOnly ? 1 : 0,
            ts: this.targetIds,
            p: this.pin,
++            s: this.status,
++            et: this.endTime,
++            ct: this.connectTime,
        }
        payload.binaryContent = wfc.utf8_to_b64(JSON.stringify(obj));
        return payload;
    }

    decode(payload) {
        super.decode(payload);
        this.callId = payload.content;
        let json = wfc.b64_to_utf8(payload.binaryContent);
        let obj = JSON.parse(json);

        this.audioOnly = (obj.a === 1);
        this.targetIds = obj.ts
        this.pin = obj.p;
++        this.status = obj.s
++        this.endTime = obj.et
++        this.connectTime = obj.ct
    }
}
```

2. 在对应的消息 UI 中添加对应的状态描述，其逻辑和 [CallStartMessageContentView.vue](https://github.com/wildfirechat/vue-pc-chat/blob/master/src/ui/main/conversation/message/content/CallStartMessageContentView.vue) 一致
```js
const textContent = computed(() => {
  let voip = props.message.messageContent
  let desc = i18n.t('remote.desc')
  if (voip.endTime > 0 && voip.connectTime > 0) {
    let duration = parseInt((numberValue(voip.endTime) - numberValue(voip.connectTime)) / 1000)
    desc = `远程协助已结束`
  } else {
    let reason = voip.status
    console.log({ reason })
    switch (reason) {
      case CallEndReason.REASON_Unknown:
        desc = i18n.t('voip.not_answer')
        break
      case CallEndReason.REASON_Busy:
        desc = '线路忙'
        break
      case CallEndReason.REASON_SignalError:
        desc = '网络错误'
        break
      case CallEndReason.REASON_Hangup:
        desc = '已取消'
        break
      case CallEndReason.REASON_RemoteHangup:
        desc = '对方已取消'
        break
      case CallEndReason.REASON_OpenCameraFailure:
        desc = '网络错误'
        break
      case CallEndReason.REASON_Timeout:
        desc = '未接听'
        break
      case CallEndReason.REASON_AcceptByOtherClient:
        desc = '已在其他端接听'
        break
      case CallEndReason.REASON_AllLeft:
        desc = '通话已结束'
        break
      case CallEndReason.RemoteBusy:
        desc = '对方忙'
        break
      case CallEndReason.RemoteTimeout:
        desc = '对方未接听'
        break
      case CallEndReason.RemoteNetworkError:
        desc = '对方网络错误'
        break
      case CallEndReason.RoomDestroyed:
        desc = '通话已结束'
        break
      case CallEndReason.RoomNotExist:
        desc = '通话已结束'
        break
      case CallEndReason.RoomParticipantsFull:
        desc = ' 已达最大通话人数'
        break
      default:
        break
    }
  }
  return desc
})
```

我不确定我是否理解有误，我认为这个 `status` 状态 会在 [avenginekitproxy.js
 #updateCallStartMessageContentListener](https://github.com/wildfirechat/vue-pc-chat/blob/master/src/wfc/av/engine/avenginekitproxy.js#L92) 中被更新，所以我在此处打了断点，在接受远程共享画面请求并建立完成时，这个回调拿到的 `status` 是 0，也就是进到了 [voip.not_answer](https://github.com/wildfirechat/vue-pc-chat/blob/master/src/ui/main/conversation/message/content/CallStartMessageContentView.vue#L52) 中，我想知道这个 0 是否只是代表 **已连接** 而不是 not_answer ？
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/41190f96-bf81-4d72-bdfc-633b4f75ae89" />

**Comment by imndx** [comment]
`updateCallStartMessageContentListener` 只会更新`CallStartMessageContent`，并不会更新远程控制/协助相关消息。

如果需要更新`RCInviteMessageContent`或者`RCRequestMessageContent`消息的话，需要在相关的回调里面去更新对应的消息。

但我们建议，采用比较中性的描述，这样的话，多端，或者本地删除消息，然后从服务端拉取历史消息等情况下，都能保持一致

**Comment by k1nz** [comment]
但在实际调试中，调用 `avenginekitproxy.requestRemoteControl` 并在对方接受之后，是会触发 `updateCallStartMessageContentListener` 回调的。

并且在 语音通话/视频通话中，接听之后 `updateCallStartMessageContentListener` 回调的 `message.content.status` 也为 0

**Comment by imndx** [comment]
你好，`status = 0` 是正常的，
`callStartMessageContent#status`表示的意义如下：

```
    /**
     * 0, UnKnown,
     * 1, Busy,
     * 2, SignalError,
     * 3, Hangup,
     * 4, MediaError,
     * 5, RemoteHangup,
     * 6, OpenCameraFailure,
     * 7, Timeout,
     * 8, AcceptByOtherClient
     */
```

`connectTime > 0`表示已连接/接通
