### ISSUE TITLE
在macOS最新版11.2频繁崩溃

### ISSUE THREAD

**Issue by internet5** [wildfirechat/vue-pc-chat#48]
在macOS最新版11.2频繁崩溃，这个是因为electron版本的原因还是什么原因

**Comment by imndx** [comment]
你好，请问如何复现？是否有相关日志？

**Comment by heavyrain2012** [comment]
我升级到11.2.2后遇到无法打开的情况，提示没有权限。查了查网上说是因为没有签名的原因，下载证书重新打包就签名了，签名后的包一切正常。请确实是不是没有签名，签名之后试试

**Comment by imndx** [comment]
另外，electron-builder 请升级到 22 +
