### ISSUE TITLE
pc 端登录，app 端没有弹出确认在pc端登录信息

### ISSUE THREAD

**Issue by lida1984** [wildfirechat/vue-pc-chat#53]
app 端转入后台的情况下，pc端登录请求发出后，app 端转入前台，未弹出请求在pc登录框.

**Comment by imndx** [comment]
你好，这是手机端的问题。

手机端收到弹出确认请求之后，会尝试弹出确认登录界面。但是如果应用权限管理里面，没有允许**后台弹出界面***，将无法弹出界面。
