### ISSUE TITLE
PC端config里的几个配置项咨询

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/vue-pc-chat#58]
关于config.js文件 
1. ICE_SERVERS，是什么作用，还有userName和password？

2. FILE_HELPER_ID 的 值怎么改吗？文件助手的个人资料会显示这个id，需要改掉。

3. 语音消息很多，建议使用CDN，启用的话应该怎么配，比如CDN使用七牛，有什么demo吗？

**Comment by imndx** [comment]
1. ICE_SERVERS，是进行音视频通话所需要的，可以参考[这儿](https://docs.wildfirechat.cn/webrtc/)
2. FILE_HELPER_ID，IM SERVER数据库中```t_user```表有相关记录，可以手动修改，或通过server api修改；需要注意的是，手动修改数据库时，需要将```_dt``` + 1，并重启服务。
3. 由于移动端发送的语音消息是```amr```格式，但浏览器不直接支持播放```amr```格式的音频，故采用```app_server```对音频文件的格式进行转换，转换之后，会存在```app_server```，通过CDN去加载这些文件，是为了降低```app_server```的压力，和提升用户体验。

PS: 我们有计划将上面3中提到的使用```app_server```进行格式转换替换成web/pc端本地进行处理

**Comment by qdhaiqiang** [comment]
3Q
