### ISSUE TITLE
node版本高于10.16.x时，dev正常，打包后启动错误

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/vue-pc-chat#62]
node版本：12.8.0 或者 14.0.0

本地dev启动成功，功能work，但是打包后，在windows平台启动报如下错误，白屏无法启动
![高版本node](https://user-images.githubusercontent.com/12232338/123978696-a9433880-d9f2-11eb-8c2b-7a4131210bc5.png)

既然dev正常，猜测是跟打包配置有关系，现在node稳定版都已经14.17.x了，希望能支持下打包，多个项目并行开发时来回切换node版本，可能会引起一些不可知的问题。

**Comment by imndx** [comment]
目前原因还在调查中

请先将node版本切换到```10.16.x```，该版本```npm run dev```和打包都正常。

**Comment by imndx** [comment]
切换到```10.16.x```之后，需要先删除```node_modules```再打包测试

**Comment by qdhaiqiang** [comment]
切换到10.16.x之后，肯定删除node_modules，然后所有的功能都ok，现在有问题的高版本的

**Comment by imndx** [comment]
如果使用```nvm```切换版本，打包之后，```electron```里面包含的```node```版本，可能不对，导致相同的问题。

----------
建议就是：直接把卸载其他版本的```node```，重新安装```10.16.x```版本

PS: ```electron```里面，可以通过控制台输入```process.versions```查看```electron```里面包含的```node```版本信息。
