### ISSUE TITLE
收藏功能的几个问题

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/vue-pc-chat#63]
收藏功能的几个问题
1. 【全部收藏】里的消息，在【聊天记录】收藏单独查看时没有数据
![image](https://user-images.githubusercontent.com/12232338/124061783-1d68f500-da62-11eb-8327-bb793df74f37.png)
![image](https://user-images.githubusercontent.com/12232338/124061796-24900300-da62-11eb-9c83-b2273cab4697.png)

2. 聊天里的消息【添加收藏】没有反应，也加入不到收藏里去。

3. 收藏里的时间错误
![image](https://user-images.githubusercontent.com/12232338/124061894-4f7a5700-da62-11eb-8626-ffab6418b801.png)
![image](https://user-images.githubusercontent.com/12232338/124061914-5c974600-da62-11eb-9bf1-2a8c85313665.png)

4. 收藏不能删除
5. 收藏里的消息右键没有转发

6. 收藏不自动刷新，如果不重启应用的话，手机端新加入的收藏电脑端看不到

**Comment by qdhaiqiang** [comment]
1. 本issue的 问题1 没有解决。
2. 加入收藏没有成功提示，用户不清楚操作结果，可能会收藏多次，建议增加收藏成功提示

**Comment by imndx** [comment]
1. 聊天记录指的是组合消息，就是合并转发产生的那种消息。
2. 已添加
