### ISSUE TITLE
搜索功能不能搜索聊天记录

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/vue-pc-chat#67]
您好，
目前搜索不能搜索聊天记录，看代码里是todo，请问是没有开放，还是没有开发？怎么计划的？

![image](https://user-images.githubusercontent.com/12232338/124743830-b317ef00-df50-11eb-8334-48d6f0f519d0.png)

![image](https://user-images.githubusercontent.com/12232338/124744023-e3f82400-df50-11eb-845c-4238a5a74de9.png)

**Comment by imndx** [comment]
目前尚未开发相关UI，对应的api接口是```wfc.searchXXXX```，UI你们可以先自行开发
