### ISSUE TITLE
自定义截图功能快捷键

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/vue-pc-chat#68]
您好，

根据文档介绍，无法找到文档中描述的相关文件，请问这个文件是在哪呢？

![image](https://user-images.githubusercontent.com/12232338/124752407-63d6bc00-df5a-11eb-9008-ac957e81cd9d.png)

我们有两个需求：
1. 能设置截图快捷键，
2. 定制鼠标右键的取消行为。

 请教下应该怎么入手，从哪里找资料实现

**Comment by imndx** [comment]
上面的截图是针对```react```版本的，不应用于```vue```版本，```vue```版本使用的插件是```electron-screenshots```

针对你的问题：
1. 请看下```background.js```里面的，```app.on('ready', () => ....```部分
2. 你看下```electron-screenshots```插件，我不太清楚他们是否有相关实现，没有的话，得你们自己去实现
