### ISSUE TITLE
登录页面扫码后显示的头像是系统默认的头像，不是用户头像

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/vue-pc-chat#70]
您好：

最近fix的[#66](https://github.com/wildfirechat/vue-pc-chat/issues/66)不够完善。扫码以后虽然不展示"二维码获取中"这句话了，但是显示了一个默认头像，没有显示出当前扫描的用户的头像。

应该是个小问题，还请优化。

![image](https://user-images.githubusercontent.com/12232338/125008695-9afdb800-e095-11eb-9989-e3e17fce71f7.png)

**Comment by imndx** [comment]
当扫码的这个人没有配置头像的时候，才会显示这个默认头像

**Comment by qdhaiqiang** [comment]
在客户端已经设置了头像的

**Comment by imndx** [comment]
那登录进去之后，左上角头像正常显示吗？

**Comment by qdhaiqiang** [comment]
貌似是我们更新代码集成的问题
