### ISSUE TITLE
在有与他人有聊天记录且从未给自己发送过消息的情况下出现的问题

### ISSUE THREAD

**Issue by wenxuancheung** [wildfirechat/vue-pc-chat#85]
条件：与他人有过聊天记录，且未给自己发送过消息
出现情况：与自己的聊天面板会出现与他人的聊天记录。
![image](https://user-images.githubusercontent.com/34408245/125758102-35474ef7-1333-40a9-9b14-9afff5de4af5.png)

**Comment by imndx** [comment]
请问下这个问题是必现的吗？有没有什么稳定的复现路径？

**Comment by imndx** [comment]
已解决，请联系我们更新专业版IM Server
