### ISSUE TITLE
显示启动成功，但是端口没有，也没有任务报错

### ISSUE THREAD

**Issue by jiruyi** [wildfirechat/vue-pc-chat#88]
![image](https://user-images.githubusercontent.com/33124055/126614387-33b71889-2d09-4770-9b78-464e7564f7e5.png)

**Comment by imndx** [comment]
你们有什么改动吗？

**Comment by jiruyi** [comment]
没有改动，就是页面看不到，才发现端口都没起来，项目不是running在8080端口嘛，那肯定能看到这个进程，结果没有

**Comment by heavyrain2012** [comment]
操作系统是linux系统吧，具体是哪个桌面，另外换个别的电脑可以吗

**Comment by qdhaiqiang** [comment]
@jiruyi 检查一下electron的安装和配置。


![image](https://user-images.githubusercontent.com/12232338/126727576-7ebcf808-e63b-4938-b4b1-711293854cf5.png)

**Comment by jiruyi** [comment]
> 操作系统是linux系统吧，具体是哪个桌面，另外换个别的电脑可以吗

是的，换了三台都不行

**Comment by jiruyi** [comment]
> @jiruyi 检查一下electron的安装和配置。
> 
> ![image](https://user-images.githubusercontent.com/12232338/126727576-7ebcf808-e63b-4938-b4b1-711293854cf5.png)

好的，我来看看
