### ISSUE TITLE
创建群搜索用户时如何检索出非好友用户

### ISSUE THREAD

**Issue by qdhaiqiang** [wildfirechat/vue-pc-chat#92]
现状：
消息页面上方搜索只能搜索好友，创建群聊，只能搜索好友。

需求：
不是好友也要能被搜索到，包括创建群、转发等场景，没有好友限制

搜索解决：
`store.js`新版本约1140行`setSearchQuery`方法，放开`searchUser`就能搜索到非好友用户了。

创建群解决：
发现创建群的搜索，跟上面的搜索逻辑不一样，指导下需要怎么做，或者能不能加个类似全局搜索这样的开关。
不需要的关闭，需要的可以打开。

感谢~~

**Comment by imndx** [comment]
现在创建群聊是限制只能选择好友，创建群聊界面的搜索，其实是在好友列表里面，进行过滤。

如果你们希望搜索到非好友的话，可以看下：

```PickUserView#filterUsers```

**Comment by qdhaiqiang** [comment]
创建群，转发这两个会显示用户和会话列表的页面都存在一样的问题。

PickUserView#filterUsers是把用户传进去根据检索条件过虑符合条件的结果。

但是我需要在`searchView#showCreateConversationModal`调用`PickUserView`组件时给users传所有用户？

这么做就算实现了也应该不合适吧？

是不是应该在建群、转发的的用户列表页也是现实实时搜索。

指导下吧，谢谢。

**Comment by imndx** [comment]
已支持，请参考```store#searchUser```
