### ISSUE TITLE
共享桌面时，分享窗口tab中，会展示出输入法窗口、windows系统通知消息等窗口，不需要出现在分享选项中，如何自定义分享列表中的分享窗口选项

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/vue-pc-chat#94]

**Comment by imndx** [comment]
有个比较简单粗暴的办法：

```ScreenOrWindowPicker.vue```里面，调用```desktopCapturer.getSources```的地方，对```sources```根据```name```过滤一下，比如将```name```为 新通知 的窗口过滤掉
