### ISSUE TITLE
在没有麦克风、摄像头的设备上，加入或发起会议，直接是会议窗口黑屏，需要针对硬件条件进行业务处理

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/vue-pc-chat#95]
在没有麦克风、摄像头、声卡等硬件的PC设备上，点击开始会议或加入别人的会议，现在是黑屏，需要提供可用硬件的列表，如果为空，则可做相应的业务判断，例如在会议窗口中弹出提示，告知没有音视频设备，点击弹窗可关闭整个会议窗口

**Comment by imndx** [comment]
这个错误处理，可以参考 https://github.com/dillonchanis/vue-error-boundary

**Comment by imndx** [comment]
已支持自定义UI处理，请更新到最新代码。
