### ISSUE TITLE
PC分享桌面分享微信窗口时，分享画面黑屏，显示不出微信窗口

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/vue-pc-chat#97]

**Comment by imndx** [comment]
这个好像是因为微信限制录屏导致的

**Comment by imndx** [comment]
https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/#12060883410030199

**Comment by imndx** [comment]
mac 系统更新到 ```11.6 (20G165)```只有，不会出现黑屏了。
